from typing import List, Optional, Union

class QSConnection:
    def __init__(self, host: str, port: int = 7443, connection_type: str = "Auto") -> None: ...
    def run_command(self, command: Union[str, bytes]) -> MessageResponse: ...
    def run_command_bytes(self, bytes: bytes) -> MessageResponse: ...
    def subscribe_log(self, topics: List[str]) -> LogReceiver: ...
    def connected(self) -> bool: ...

class MessageResponse:
    def get_response(self) -> str: ...
    def __next__(self) -> str: ...
    def get_ack(self) -> str: ...
    def get_response_with_timeout(self, timeout: int) -> str: ...

class LogReceiver:
    def __next__(self) -> LogMessage: ...
    def next(self) -> LogMessage: ...

class LogMessage:
    topic: str
    message: str
