# SPDX-FileCopyrightText: 2021-2023 Constantine Evans <qslib@mb.costi.net>
# SPDX-License-Identifier: EUPL-1.2

import asyncio
import hashlib
import os
import time
import uuid
from pathlib import Path

import pytest

from qslib import AccessLevel, Experiment, Machine, PlateSetup, Protocol, Stage
from qslib.experiment import MachineBusyError
from qslib.machine import AlreadyCollectedError
from qslib.server import ServerError, ServerUnavailable


# Machine configuration from environment variables
TEST_MACHINE = os.environ.get("QSLIB_TEST_MACHINE", "localhost")
TEST_PORT = int(os.environ.get("QSLIB_TEST_PORT", "7443"))
TEST_PASSWORD = os.environ.get("QSLIB_TEST_PASSWORD", "")
TEST_SSL = os.environ.get("QSLIB_TEST_SSL", "true").lower() in ("true", "1", "yes")

# qslib-server is deployed onto the machine so that it shares the machine's
# filesystem; without that, the file and experiment resources would read a
# different tree than SCPI does.
TEST_SERVER_BINARY = os.environ.get("QSLIB_TEST_SERVER_BINARY")
TEST_SERVER_PORT = os.environ.get("QSLIB_TEST_SERVER_PORT")
TEST_SERVER_TOKEN = os.environ.get("QSLIB_TEST_SERVER_TOKEN")
TEST_SERVER_FILE_ROOT = os.environ.get("QSLIB_TEST_SERVER_FILE_ROOT", "/data/vendor/IS")
# ensure_server sends the launch line to /dev/null, so the server's own --log
# is the only way to see why a deployment or a request failed.
TEST_SERVER_LOG = os.environ.get("QSLIB_TEST_SERVER_LOG", "/data/qslib-server.log")
TEST_SERVER_SCPI_TARGET = os.environ.get("QSLIB_TEST_SERVER_SCPI_TARGET", "127.0.0.1:7000")

requires_machine = pytest.mark.skipif(
    os.environ.get("QSLIB_TEST_MACHINE") is None, reason="No test machine configured (set QSLIB_TEST_MACHINE env var)"
)


def _machine(*, server: bool = False) -> Machine:
    kwargs = {}
    if server:
        kwargs["server_port"] = int(TEST_SERVER_PORT)
        kwargs["server_token"] = TEST_SERVER_TOKEN
    return Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL, **kwargs)


def _retire_stale_server(m: Machine, expected_sha: str) -> None:
    """Stop a deployed qslib-server that is not the binary under test.

    ensure_server refuses to redeploy over anything answering /health, so a
    server left by an earlier run would otherwise be reused silently, or fail
    the run outright if it holds a different token.
    """
    client = m.server
    assert client is not None
    try:
        health = client.health()
        # A server that never reaches ready (e.g. launched against the wrong
        # SCPI target) is useless but still answers /health, which is enough
        # to make ensure_server refuse to replace it. Retire it too.
        if health.get("executable_sha256") == expected_sha and health.get("ready") is True:
            return
    except ServerUnavailable:
        return  # nothing listening; ensure_server will deploy
    except ServerError:
        pass  # answering but unusable (e.g. a stale token); replace it

    with m.ensured_connection(AccessLevel.Controller):
        # (Text below generated by LLM)
        # Real instruments have pkill through busybox, but the simulator image
        # CI runs against has no procps at all (no pkill, pgrep, ps or killall)
        # and kill only as a shell builtin, where `pkill ... || true` exited 127
        # and silently stopped nothing. Match the process name in /proc instead,
        # which works on both. Matching on comm rather than the command line
        # avoids killing the SYST:EXEC shell running this.
        #
        # Backticks, not $(...), and a named variable, not $1: the
        # InstrumentServer substitutes ${...}, $(...) and $<digit> itself before
        # the shell ever sees them ($0 yields the previous command's output).
        m.run_command('SYST:EXEC "for p in `grep -l qslib-server /proc/[0-9]*/comm | cut -d/ -f3`; do kill $p; done"')

    deadline = time.monotonic() + 10
    while time.monotonic() < deadline:
        try:
            client.health()
        except ServerUnavailable:
            return
        except ServerError:
            pass
        time.sleep(0.2)
    raise RuntimeError(
        "stale qslib-server still answering /health after kill; check that the "
        "instrument shell has grep and cut and that the process is named qslib-server"
    )


@pytest.fixture(scope="session")
def deployed_server() -> Machine:
    """Deploy qslib-server onto the machine and return a Machine using it.

    Deployment is the first assertion: it exercises the SCPI binary push,
    chmod, and SYST:EXEC launch, which unit tests can only reach with
    _deploy_binary monkeypatched.
    """
    if TEST_SERVER_BINARY is None or TEST_SERVER_PORT is None:
        pytest.skip("no qslib-server configured (set QSLIB_TEST_SERVER_BINARY and QSLIB_TEST_SERVER_PORT)")
    if not TEST_SERVER_TOKEN:
        pytest.skip("QSLIB_TEST_SERVER_TOKEN is required: a token bootstrap is what enables writes and controls")

    m = _machine(server=True)
    expected_sha = hashlib.sha256(Path(TEST_SERVER_BINARY).read_bytes()).hexdigest()
    _retire_stale_server(m, expected_sha)
    m.ensure_server(
        binary=TEST_SERVER_BINARY,
        listen=f"0.0.0.0:{TEST_SERVER_PORT}",
        file_root=TEST_SERVER_FILE_ROOT,
        extra_args=(
            "--log",
            TEST_SERVER_LOG,
            "--scpi-target",
            TEST_SERVER_SCPI_TARGET,
            "--scpi-password",
            TEST_PASSWORD,
        ),
    )

    client = m.server
    assert client is not None
    health = client.health()
    assert health["ready"] is True
    assert health["executable_sha256"] == expected_sha, "a different qslib-server build answered after deployment"

    # _server_for declines whenever a manual connection is open, so a
    # connection left behind by the deploy would route every server-variant
    # test back to SCPI and fail assert_no_scpi with a confusing message.
    assert not m.connected, "deployment left a SCPI connection open"
    return m


class _ScpiSpy:
    """Counts the direct SCPI connections a Machine opens."""

    def __init__(self, original):
        self.original = original
        self.count = 0

    def __call__(self, *args, **kwargs):
        self.count += 1
        return self.original(*args, **kwargs)


def _install_spy(m: Machine) -> _ScpiSpy:
    """Wrap ``m._direct_connection`` with a counter, once per Machine."""
    spy = getattr(m, "_test_scpi_spy", None)
    if spy is None:
        spy = _ScpiSpy(m._direct_connection)
        m._direct_connection = spy
        m._test_scpi_spy = spy
    return spy


@pytest.fixture(params=["direct", "server"])
def machine(request) -> Machine:
    """A Machine reaching the instrument directly over SCPI, or via qslib-server."""
    if request.param == "server":
        m = request.getfixturevalue("deployed_server")
    else:
        m = _machine()
    _install_spy(m).count = 0
    m._test_transport = request.param
    return m


def reset_scpi_count(m: Machine) -> None:
    """Restart the SCPI counter, to scope assert_no_scpi to part of a test."""
    spy = getattr(m, "_test_scpi_spy", None)
    if spy is not None:
        spy.count = 0


def assert_no_scpi(m: Machine) -> None:
    """Assert the preceding operation went over HTTP rather than falling back.

    _server_for falls back to direct SCPI on most failures, so without
    this a broken HTTP path would still pass every assertion in these tests.
    A no-op for the direct parametrisation.
    """
    if getattr(m, "_test_transport", None) != "server":
        return
    count = m._test_scpi_spy.count
    assert count == 0, f"operation opened {count} direct SCPI connection(s) instead of using qslib-server"


@requires_machine
@pytest.mark.asyncio
async def test_real_insufficientaccess():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        with pytest.raises(Exception):
            m.run_command("MACRO USER?")


@requires_machine
@pytest.mark.asyncio
async def test_real_accesslevelexceeded():
    m = Machine(TEST_MACHINE, port=TEST_PORT, max_access_level="Full", password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        with pytest.raises(Exception):
            m.set_access_level(AccessLevel.Full)


@requires_machine
def test_above_self_access_limit():
    m = Machine(TEST_MACHINE, port=TEST_PORT, max_access_level="Observer", password=TEST_PASSWORD, ssl=TEST_SSL)
    with pytest.raises(ValueError):
        m.set_access_level(AccessLevel.Controller)
    with m:
        assert m.access_level == AccessLevel.Observer


@requires_machine
@pytest.mark.asyncio
async def test_real_autherror():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password="aninvalidpassword", ssl=TEST_SSL)
    with pytest.raises(Exception):
        with m:
            m.run_command("HELP?")


@requires_machine
def test_real_invocationerror():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        with pytest.raises(Exception):
            m.run_command("HELP? A B")


@requires_machine
@pytest.mark.parametrize("encoding", ["base64", "plain"])
def test_file_read_write_default(machine, encoding):
    m = machine
    m.write_file("public_run_complete:test.txt", "Hello, world!")

    assert "public_run_complete:test.txt" in m.list_files("public_run_complete:")

    # list_files above and run_command below always use SCPI; only the
    # transfers have an HTTP path, so the guard covers just those.
    reset_scpi_count(m)

    data = m.read_file("public_run_complete:test.txt", encoding=encoding)
    assert data == b"Hello, world!"

    assert data == m.read_file("test.txt", context="public_run_complete", encoding=encoding)
    assert data == m.read_file("test.txt", context="public_run_complete:", encoding=encoding)

    assert_no_scpi(m)

    with m.at_access(AccessLevel.Controller):
        m.run_command("FILE:REMOVE public_run_complete:test.txt")

    assert "public_run_complete:test.txt" not in m.list_files("public_run_complete:")


@requires_machine
def test_file_written_over_scpi_is_readable_over_http(deployed_server):
    """The deployed server must see the same filesystem the vendor server does."""
    m = deployed_server
    name = f"crosstransport-{uuid.uuid4().hex[:8]}.txt"
    payload = b"shared filesystem check"

    direct = _machine()
    with direct:
        with direct.at_access(AccessLevel.Controller):
            direct.write_file(f"public_run_complete:{name}", payload, fast=False)

    spy = _install_spy(m)
    try:
        spy.count = 0
        assert m.read_file(f"public_run_complete:{name}") == payload
        assert spy.count == 0, "read fell back to SCPI; the server may not share the filesystem"
    finally:
        with direct:
            with direct.at_access(AccessLevel.Controller):
                direct.run_command(f"FILE:REMOVE public_run_complete:{name}")


# @pytest.mark.asyncio
# async def test_real_fakeexperiment():
#     exp = Experiment.from_file("tests/test.eds")
#     # We need better sample arrangements:
#     exp.sample_wells["Sample 1"] = ["A7", "A8"]
#     exp.sample_wells["Sample 2"] = ["A9", "A10"]
#     exp.sample_wells["othersample"] = ["B7"]

#     with Machine(TEST_MACHINE) as m:
#         with m.at_access("Controller"):
#             exp._populate_folder(m)


@requires_machine
@pytest.mark.asyncio
async def test_real_experiment(machine):
    proto = Protocol(
        [Stage.stepped_ramp(50, [30, 31, 32, 33, 34, 35], 240, n_steps=10, collect=True)],
        filters=["x1-m4", "x3-m5"],
    )

    exp = Experiment(uuid.uuid1().hex, proto, PlateSetup({"s": "A1"}))

    m = machine

    exp.run(m, require_drawer_check=False)

    exp.pause_now()

    with pytest.raises(MachineBusyError, match=rf"Machine {TEST_MACHINE}:[^ ]+ is currently busy: .*"):
        exp.run(m)

    exp.sync_from_machine(m)

    proto2 = Protocol(
        [
            Stage.stepped_ramp(50, [30, 31, 32, 33, 34, 35], 240, n_steps=10, collect=True),
            Stage.stepped_ramp(30, 50, 120, n_steps=5, collect=True),
        ],
        filters=["x1-m4", "x3-m5"],
    )

    assert proto != proto2
    assert proto != 5

    exp.change_protocol(proto2)

    exp2 = Experiment.from_running(m)

    # assert exp.protocol == exp2.protocol
    assert exp.name == exp2.name

    exp.resume()

    # qslib-server provides a running experiment's status; check it did not fall back.
    reset_scpi_count(m)
    exp.get_status()
    assert_no_scpi(m)

    exp.sync_from_machine(m)

    rs = m.run_status()
    while rs.name != "-":
        await asyncio.sleep(1)
        rs = m.run_status()

    exp.sync_from_machine(m)

    exp3 = Experiment.from_machine(m, exp.name)

    assert exp2.name == exp3.name

    rs = m.run_status()

    assert rs.name == "-"

    with m:
        with m.at_access("Controller"):
            m.compile_eds(exp.name)

    exp_from_eds = Experiment.from_machine(m, exp.name)
    assert exp_from_eds.name == exp.name

    with pytest.raises(AlreadyCollectedError):
        m.compile_eds(exp.name)


@requires_machine
def test_block_temp(machine):
    assert machine.block == (False, 25.0)
    assert_no_scpi(machine)


@requires_machine
def test_run_status_idle(machine):
    rs = machine.run_status()
    assert rs.name == "-"
    assert_no_scpi(machine)


@requires_machine
def test_machine_status(machine):
    ms = machine.machine_status()
    assert hasattr(ms, "drawer")
    assert hasattr(ms, "sample_temperatures")
    assert_no_scpi(machine)


@requires_machine
def test_get_running_protocol_no_run(machine):
    with pytest.raises(ValueError, match="Nothing is currently running"):
        machine.get_running_protocol()
    assert_no_scpi(machine)


@requires_machine
def test_get_zone_count(machine):
    z = machine.get_zone_count()
    assert z >= 1
    assert_no_scpi(machine)


@requires_machine
def test_list_runs_in_storage(machine):
    runs = machine.list_runs_in_storage()
    assert isinstance(runs, list)
    assert_no_scpi(machine)


@requires_machine
def test_list_runs_in_storage_verbose(machine):
    runs = machine.list_runs_in_storage(verbose=True)
    assert isinstance(runs, list)
    assert_no_scpi(machine)


@requires_machine
def test_power_status(machine):
    p = machine.power
    assert isinstance(p, bool)
    assert_no_scpi(machine)


@requires_machine
def test_drawer_position(machine):
    d = machine.drawer_position
    assert d in ("Open", "Closed", "Unknown")
    assert_no_scpi(machine)


@requires_machine
def test_block_temperature(machine):
    b = machine.block
    assert isinstance(b, tuple) and len(b) == 2
    assert_no_scpi(machine)


@requires_machine
def test_run_command_help():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        result = m.run_command("HELP?")
        assert isinstance(result, str) and len(result) > 0


@requires_machine
def test_cover_position(machine):
    pos = machine.cover_position
    assert pos in ("Up", "Down", "Unknown", "")
    assert_no_scpi(machine)


@requires_machine
def test_drawer_open_close():
    # Direct only: qslib-server verifies the drawer reaches Open, while the
    # SCPI path's drawer_open() is a bare OPEN with no check.
    m = _machine()
    with m:
        m.drawer_open()
        m.drawer_close(lower_cover=False, check=False)


@requires_machine
def test_cover_lower(machine):
    # Close drawer first, then lower cover
    machine.drawer_close(lower_cover=False, check=False)
    machine.cover_lower(check=False)
    assert_no_scpi(machine)


@requires_machine
def test_run_command_to_bytes():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        result = m.run_command_to_bytes("HELP?")
        assert isinstance(result, bytes) and len(result) > 0


@requires_machine
def test_run_command_bytes_raw():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        result = m.run_command_bytes(b"HELP?")
        assert isinstance(result, bytes) and len(result) > 0


@requires_machine
def test_define_protocol():
    proto = Protocol(
        [Stage.stepped_ramp(50, 60, 120, n_steps=3, collect=True)],
        filters=["x1-m4"],
        name="TestProto",
    )
    m = Machine(
        TEST_MACHINE,
        port=TEST_PORT,
        max_access_level="Controller",
        password=TEST_PASSWORD,
        ssl=TEST_SSL,
    )
    with m:
        m.define_protocol(proto)


@requires_machine
def test_list_files_verbose():
    # list_files is @_ensure_connection-decorated and has no HTTP path,
    # so there is nothing for the server parametrisation to exercise.
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        result = m.list_files("public_run_complete:", verbose=True)
        assert isinstance(result, list)
        # Each entry should be a dict with at least 'path'
        for entry in result:
            assert isinstance(entry, dict)
            assert "path" in entry


@requires_machine
def test_current_run_name_no_run(machine):
    name = machine.current_run_name
    assert name is None
    assert_no_scpi(machine)


@requires_machine
def test_at_access_context_manager():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        initial = m.access_level
        with m.at_access("Controller"):
            assert m.get_access_level()[0] == AccessLevel.Controller
        # After exiting context, should restore previous level
        restored = m.get_access_level()[0]
        assert restored == initial


@requires_machine
def test_block_setter_off(machine):
    machine.block = False
    on, temp = machine.block
    assert on is False
    assert_no_scpi(machine)


@requires_machine
def test_block_setter_tuple(machine):
    machine.block = (True, 30.0)
    on, temp = machine.block
    assert on is True
    assert abs(temp - 30.0) < 1.0
    # Clean up: turn block off
    machine.block = False
    assert_no_scpi(machine)


@requires_machine
def test_generate_random_key():
    m = Machine(
        TEST_MACHINE,
        port=TEST_PORT,
        max_access_level="Controller",
        password=TEST_PASSWORD,
        ssl=TEST_SSL,
    )
    with m:
        key = m.generate_random_key()
        assert isinstance(key, str)
        assert len(key) > 0


@requires_machine
def test_power_cycle(machine):
    original = machine.power
    machine.power = True
    assert machine.power is True
    machine.power = False
    assert machine.power is False
    # Restore
    machine.power = original
    assert_no_scpi(machine)


@requires_machine
def test_get_expfile_list():
    m = Machine(TEST_MACHINE, port=TEST_PORT, password=TEST_PASSWORD, ssl=TEST_SSL)
    with m:
        # This may return an empty list or a list of files
        try:
            result = m.get_expfile_list("*", allow_nomatch=True)
            assert isinstance(result, list)
        except Exception:
            pass  # May fail if no experiment is running
