# SPDX-FileCopyrightText: 2021-2023 Constantine Evans <qslib@mb.costi.net>
# SPDX-License-Identifier: EUPL-1.2

"""Unit tests for Machine class — pure logic, no network required."""

from contextlib import nullcontext

import pytest

from qslib import (
    AccessLevel,
    Machine,
    StatusLedColor,
    StatusLedMode,
    StatusLedSet,
    StatusLedState,
)
from qslib.machine import _gen_auth_response
from qslib.scpi_commands import SCPICommand


# --- Machine default params ---


def test_machine_default_params():
    m = Machine("example.com")
    assert m.host == "example.com"
    assert m.port == 7443  # default SSL port
    assert m.ssl is None
    assert m.automatic is True


def test_machine_ssl_false_defaults_port_7000():
    m = Machine("example.com", ssl=False)
    assert m.port == 7000
    assert m.ssl is False


def test_machine_custom_port_overrides():
    m = Machine("example.com", port=9999, ssl=False)
    assert m.port == 9999


def test_machine_ssl_true_default_port():
    m = Machine("example.com", ssl=True)
    assert m.port == 7443


def test_machine_server_settings_asdict():
    m = Machine("example.com", server_port=7500, server_token="secret")
    assert m.asdict()["server_port"] == 7500
    assert "server_token" not in m.asdict()
    assert m.asdict(password=True)["server_token"] == "secret"


def test_get_running_protocol_idle_direct_connection(monkeypatch):
    machine = Machine("instrument")
    commands: list[str] = []
    monkeypatch.setattr(machine, "ensured_connection", lambda *_args, **_kwargs: nullcontext(machine))

    def run_command(command):
        commands.append(command)
        return ""

    monkeypatch.setattr(machine, "run_command", run_command)

    with pytest.raises(ValueError, match="Nothing is currently running"):
        machine.get_running_protocol()

    assert commands == ["RET ${Protocol} ${SampleVolume} ${RunMode}"]


# --- connect() always means a manually owned direct SCPI session ---


class _FakeConn:
    """Stand-in for a QSConnection; ``connected()`` is False so Machine.__del__
    does not try to disconnect a sentinel at teardown.

    (Text above generated by LLM)
    """

    def connected(self):
        return False

    def disconnect(self):
        pass


def _stub_post_connect(monkeypatch, m):
    monkeypatch.setattr(m, "set_access_level", lambda *a, **k: None)
    monkeypatch.setattr(m, "get_access_level", lambda: (AccessLevel.Observer,))


def test_connect_is_direct_when_secure(monkeypatch):
    m = Machine("h", ssl=True, client_certificate_path="/c.pem")
    direct = _FakeConn()

    monkeypatch.setattr(m, "_direct_connection", lambda: direct)
    _stub_post_connect(monkeypatch, m)
    m.connect()
    assert m._connection is direct


def test_connect_is_direct_even_when_server_is_configured(monkeypatch):
    """A configured HTTP API never replaces explicit/manual connect()."""
    m = Machine("h", server_port=7500)
    direct = _FakeConn()
    monkeypatch.setattr(m, "_direct_connection", lambda: direct)
    _stub_post_connect(monkeypatch, m)
    m.connect()
    assert m._connection is direct


def test_connect_does_not_probe_optional_server(monkeypatch):
    m = Machine("h", server_port=7500)
    direct = _FakeConn()
    monkeypatch.setattr(m, "_direct_connection", lambda: direct)
    _stub_post_connect(monkeypatch, m)
    m.connect()
    assert m._connection is direct


def test_connect_does_not_probe_server_by_default(monkeypatch):
    """Ordinary connections stay on the existing direct Auto path unless the
    caller explicitly opts into qslib-server with server_port."""
    m = Machine("h")
    direct = _FakeConn()

    monkeypatch.setattr(m, "_direct_connection", lambda: direct)
    _stub_post_connect(monkeypatch, m)
    m.connect()
    assert m._connection is direct


# --- set_access_level validation ---


def test_set_access_level_above_max_raises():
    m = Machine("example.com", max_access_level="Observer")
    with pytest.raises(ValueError, match="above maximum"):
        m.set_access_level(AccessLevel.Controller)


def test_max_access_level_property():
    m = Machine("example.com", max_access_level="Controller")
    assert m.max_access_level == AccessLevel.Controller
    m.max_access_level = "Observer"
    assert m.max_access_level == AccessLevel.Observer


# --- _gen_auth_response ---


def test_gen_auth_response():
    # HMAC-MD5 is deterministic — verify known computation
    result = _gen_auth_response("testpassword", "123456")
    assert isinstance(result, str)
    assert len(result) == 32  # MD5 hex digest
    # Verify determinism
    assert result == _gen_auth_response("testpassword", "123456")
    # Different password → different result
    assert result != _gen_auth_response("otherpassword", "123456")


# --- asdict ---


def test_asdict_without_password():
    m = Machine("example.com", password="secret")
    d = m.asdict()
    assert d["host"] == "example.com"
    assert "password" not in d


def test_asdict_with_password():
    m = Machine("example.com", password="secret")
    d = m.asdict(password=True)
    assert d["password"] == "secret"


def test_asdict_minimal():
    m = Machine("example.com")
    d = m.asdict()
    # host is always present; port is included since ssl=None → default 7443
    assert d["host"] == "example.com"
    assert "password" not in d


# --- connection property ---


def test_connection_property_raises():
    m = Machine("example.com")
    with pytest.raises(ConnectionError):
        _ = m.connection


def test_connected_false_initially():
    m = Machine("example.com")
    assert m.connected is False


@pytest.mark.parametrize("state", [False, True])
def test_connected_calls_underlying_connection(state):
    class Connection:
        def connected(self):
            return state

        def disconnect(self):
            pass

    m = Machine("example.com")
    m._connection = Connection()
    assert m.connected is state


def test_command_helpers_convert_scpi_commands_for_rust_binding():
    submitted: list[tuple[str, object]] = []

    class Response:
        def get_ack(self):
            return None

        def get_response_bytes(self):
            return b"response"

    class Connection:
        def connected(self):
            return True

        def run_command(self, command):
            submitted.append(("command", command))
            return Response()

        def run_command_bytes(self, command):
            submitted.append(("bytes", command))
            return Response()

        def disconnect(self):
            pass

    command = SCPICommand("TEST", "argument")
    machine = Machine("example.com", automatic=False)
    machine._connection = Connection()

    assert machine.run_command_to_ack(command) is None
    assert machine.run_command_bytes(command) == b"response"
    assert submitted == [
        ("command", command.to_string()),
        ("bytes", command.to_string().encode()),
    ]


def test_disconnect_noop():
    m = Machine("example.com")
    # Should not raise when not connected
    m.disconnect()
    assert m.connected is False


# --- set_access_level edge cases ---


def test_set_access_level_at_max():
    m = Machine("example.com", max_access_level="Observer")
    # Setting to Observer (same as max) should not raise ValueError
    # (it will fail at the network level, but we're testing the validation)
    # The ValueError is only raised when *above* max
    try:
        m.set_access_level(AccessLevel.Observer)
    except ConnectionError:
        pass  # Expected — not connected
    except Exception:
        pass  # Other connection errors are fine


# --- block setter validation ---


def test_block_setter_invalid():
    m = Machine("example.com")
    with pytest.raises((ValueError, ConnectionError)):
        m.block = "invalid"


# --- FilterDataFilename ---


def test_filter_data_filename_roundtrip():
    from qslib.machine import FilterDataFilename

    fn = FilterDataFilename.fromstring("S01_C003_T02_P0001_M4_X1_filterdata.xml")
    assert fn.stage == 1
    assert fn.cycle == 3
    assert fn.step == 2
    assert fn.point == 1
    assert fn.tostring() == "S01_C003_T02_P0001_M4_X1_filterdata.xml"


def test_filter_data_filename_is_same_point():
    from qslib.machine import FilterDataFilename

    fn1 = FilterDataFilename.fromstring("S01_C003_T02_P0001_M4_X1_filterdata.xml")
    fn2 = FilterDataFilename.fromstring("S01_C003_T02_P0001_M3_X2_filterdata.xml")
    fn3 = FilterDataFilename.fromstring("S01_C003_T02_P0002_M4_X1_filterdata.xml")
    assert fn1.is_same_point(fn2)  # Same point, different filter
    assert not fn1.is_same_point(fn3)  # Different point


# --- asdict with all fields ---


def test_asdict_all_fields():
    m = Machine(
        "example.com",
        port=9000,
        password="secret",
        ssl=True,
        max_access_level="Administrator",
        automatic=False,
    )
    d = m.asdict(password=True)
    assert d["host"] == "example.com"
    assert d["port"] == 9000
    assert d["password"] == "secret"
    assert d["ssl"] is True
    assert d["max_access_level"] == "Administrator"
    assert d["automatic"] is False


# --- repr ---


def test_repr():
    m = Machine("example.com")
    r = repr(m)
    assert "Machine" in r
    assert "example.com" in r


# --- Status LED types ---


def test_status_led_color_from_string():
    assert StatusLedColor("green") == StatusLedColor.Green
    assert StatusLedColor("GREEN") == StatusLedColor.Green
    assert StatusLedColor.Green != "green"
    assert StatusLedColor.Green.value == "GREEN"
    assert StatusLedColor.Red.number == 1
    assert StatusLedColor.Green.number == 2
    assert StatusLedColor.White.number == 7


def test_status_led_color_invalid():
    with pytest.raises(ValueError):
        StatusLedColor("chartreuse")


def test_status_led_mode_from_string():
    assert StatusLedMode("on") == StatusLedMode.On
    assert StatusLedMode("BLINK") == StatusLedMode.Blink
    assert StatusLedMode.On != "on"
    # boolean-normalized forms returned by LED:STATus?
    assert StatusLedMode("true") == StatusLedMode.On
    assert StatusLedMode("false") == StatusLedMode.Off


def test_status_led_mode_invalid():
    with pytest.raises(ValueError):
        StatusLedMode("flash")


def test_status_led_types_obey_hash_contract():
    color = StatusLedColor("green")
    mode = StatusLedMode("on")
    assert {StatusLedColor.Green: "green"}[color] == "green"
    assert {StatusLedMode.On: "on"}[mode] == "on"


def test_status_led_set_command_string():
    assert StatusLedSet("green", "on").command_string() == "LED:GREENON"
    assert StatusLedSet("blue", "blink").command_string() == "LED:BLUEBLINK"
    assert StatusLedSet(StatusLedColor.Red, StatusLedMode.Off).command_string() == "LED:REDOFF"


def test_status_led_state_command():
    assert StatusLedState.command() == b"LED:STATus?"


def test_status_led_state_cannot_be_constructed_directly():
    with pytest.raises(TypeError):
        StatusLedState()


def test_status_led_state_from_bytes_on():
    s = StatusLedState.from_bytes(response=b"BLUE true")
    assert s.color == StatusLedColor.Blue
    assert s.mode == StatusLedMode.On


def test_status_led_state_from_bytes_off():
    s = StatusLedState.from_bytes(b"- false")
    assert s.color is None
    assert s.mode == StatusLedMode.Off


def test_status_led_state_from_bytes_blink():
    s = StatusLedState.from_bytes(b"GREEN BLINK")
    assert s.color == StatusLedColor.Green
    assert s.mode == StatusLedMode.Blink
