//! Bounded process-local event history used by SSE clients.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use tokio::sync::{broadcast, watch};
use uuid::Uuid;

pub const EVENT_HISTORY: usize = 4096;
pub const SUBSCRIBER_BUFFER: usize = 256;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventEnvelope {
    /// Opaque SSE cursor. Consumers must not parse or perform arithmetic on it.
    pub id: String,
    pub event: String,
    pub timestamp: DateTime<Utc>,
    pub data: Value,
    /// Optional identity allowed to receive this event. This is transport
    /// metadata and is never included in the SSE payload.
    ///
    /// (Text above generated by LLM)
    #[serde(skip)]
    pub(crate) audience: Option<String>,
}

#[derive(Clone)]
pub struct EventHub {
    epoch: Arc<str>,
    next_id: Arc<AtomicU64>,
    history: Arc<Mutex<VecDeque<EventEnvelope>>>,
    sender: broadcast::Sender<EventEnvelope>,
    shutdown: watch::Sender<bool>,
}

pub enum Replay {
    Events(Vec<EventEnvelope>),
    Reset {
        reason: &'static str,
        cursor: String,
    },
}

impl EventHub {
    pub fn new() -> Self {
        let (sender, _) = broadcast::channel(SUBSCRIBER_BUFFER);
        let (shutdown, _) = watch::channel(false);
        Self {
            epoch: Arc::from(Uuid::new_v4().to_string()),
            next_id: Arc::new(AtomicU64::new(1)),
            history: Arc::new(Mutex::new(VecDeque::with_capacity(EVENT_HISTORY))),
            sender,
            shutdown,
        }
    }

    pub fn publish(&self, event: impl Into<String>, data: Value) -> EventEnvelope {
        self.publish_with_audience(None, event.into(), data)
    }

    /// Publish an event visible only to one authenticated identity (and to
    /// administrators). Used for operation resources, whose results may
    /// contain credentials or other caller-private data.
    ///
    /// (Text above generated by LLM)
    pub fn publish_for(
        &self,
        audience: impl Into<String>,
        event: impl Into<String>,
        data: Value,
    ) -> EventEnvelope {
        self.publish_with_audience(Some(audience.into()), event.into(), data)
    }

    fn publish_with_audience(
        &self,
        audience: Option<String>,
        event: String,
        data: Value,
    ) -> EventEnvelope {
        let mut history = self.history.lock().expect("event history poisoned");
        let sequence = self.next_id.fetch_add(1, Ordering::Relaxed);
        let envelope = EventEnvelope {
            id: self.cursor(sequence),
            event,
            timestamp: Utc::now(),
            data,
            audience,
        };
        if history.len() == EVENT_HISTORY {
            history.pop_front();
        }
        history.push_back(envelope.clone());
        // Send while the history lock is held. This lets
        // replay_and_subscribe establish a boundary with neither a gap nor a
        // duplicate, and serializes cursor order with history order.
        let _ = self.sender.send(envelope.clone());
        envelope
    }

    /// Replay after an opaque cursor. A bare integer is accepted as a legacy
    /// cursor in the current server epoch.
    pub fn replay_after(&self, last_id: Option<&str>) -> Replay {
        let history = self.history.lock().expect("event history poisoned");
        self.replay_locked(last_id, &history)
    }

    pub fn replay_and_subscribe(
        &self,
        last_id: Option<&str>,
    ) -> (Replay, broadcast::Receiver<EventEnvelope>) {
        let history = self.history.lock().expect("event history poisoned");
        let receiver = self.sender.subscribe();
        let replay = match last_id {
            // (Text below generated by LLM)
            // A fresh consumer needs a baseline just as much as one whose
            // cursor expired. Establish the live receiver and its cursor under
            // the same history lock, then let the HTTP handler await Status;
            // events emitted during that snapshot remain buffered after it.
            None => self.reset("initial_snapshot"),
            Some(last_id) => self.replay_locked(Some(last_id), &history),
        };
        (replay, receiver)
    }

    fn replay_locked(&self, last_id: Option<&str>, history: &VecDeque<EventEnvelope>) -> Replay {
        let Some(last_id) = last_id else {
            return Replay::Events(Vec::new());
        };
        let Some(last_sequence) = self.parse_cursor(last_id) else {
            return self.reset("server_epoch_changed");
        };
        if let Some(oldest) = history.front() {
            let oldest_sequence = cursor_sequence(&oldest.id).expect("server generated cursor");
            if last_sequence.saturating_add(1) < oldest_sequence {
                return self.reset("history_expired");
            }
        }
        let newest = self.next_id.load(Ordering::Relaxed).saturating_sub(1);
        if last_sequence > newest {
            return self.reset("cursor_ahead");
        }
        Replay::Events(
            history
                .iter()
                .filter(|event| {
                    cursor_sequence(&event.id).is_some_and(|sequence| sequence > last_sequence)
                })
                .cloned()
                .collect(),
        )
    }

    /// Build a reset snapshot at the current stream position without adding a
    /// synthetic item to the shared event history.
    pub fn reset_envelope(&self, cursor: String, data: Value) -> EventEnvelope {
        EventEnvelope {
            id: cursor,
            event: "reset".to_string(),
            timestamp: Utc::now(),
            data,
            audience: None,
        }
    }

    pub fn begin_shutdown(&self) {
        let _ = self.shutdown.send(true);
    }

    pub fn subscribe_shutdown(&self) -> watch::Receiver<bool> {
        self.shutdown.subscribe()
    }

    pub fn epoch(&self) -> &str {
        &self.epoch
    }

    fn cursor(&self, sequence: u64) -> String {
        format!("{}:{sequence}", self.epoch)
    }

    fn reset(&self, reason: &'static str) -> Replay {
        let sequence = self.next_id.load(Ordering::Relaxed).saturating_sub(1);
        Replay::Reset {
            reason,
            cursor: self.cursor(sequence),
        }
    }

    fn parse_cursor(&self, cursor: &str) -> Option<u64> {
        if let Ok(sequence) = cursor.parse::<u64>() {
            return Some(sequence);
        }
        let (epoch, sequence) = cursor.rsplit_once(':')?;
        (epoch == self.epoch.as_ref())
            .then(|| sequence.parse::<u64>().ok())
            .flatten()
    }

    pub fn subscribe(&self) -> broadcast::Receiver<EventEnvelope> {
        self.sender.subscribe()
    }
}

fn cursor_sequence(cursor: &str) -> Option<u64> {
    cursor.rsplit_once(':')?.1.parse().ok()
}

impl Default for EventHub {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn ids_are_monotonic_and_replay_is_ordered() {
        let hub = EventHub::new();
        let first = hub.publish("one", json!({"n": 1}));
        let second = hub.publish("two", json!({"n": 2}));
        assert!(cursor_sequence(&second.id) > cursor_sequence(&first.id));
        let Replay::Events(replayed) = hub.replay_after(Some(&first.id)) else {
            panic!("history unexpectedly expired");
        };
        assert_eq!(replayed.len(), 1);
        assert_eq!(replayed[0].id, second.id);
    }

    #[test]
    fn history_expiration_is_reported() {
        let hub = EventHub::new();
        for n in 0..=EVENT_HISTORY {
            hub.publish("event", json!({"n": n}));
        }
        assert!(matches!(
            hub.replay_after(Some("0")),
            Replay::Reset {
                reason: "history_expired",
                ..
            }
        ));
    }

    #[test]
    fn foreign_epoch_resets_and_legacy_numeric_cursors_work() {
        let hub = EventHub::new();
        let first = hub.publish("one", json!({"n": 1}));
        hub.publish("two", json!({"n": 2}));

        assert!(matches!(
            hub.replay_after(Some("00000000-0000-0000-0000-000000000000:1")),
            Replay::Reset {
                reason: "server_epoch_changed",
                ..
            }
        ));
        let Replay::Events(events) = hub.replay_after(Some("1")) else {
            panic!("legacy cursor should replay in the current epoch");
        };
        assert_eq!(events.len(), 1);
        assert_ne!(first.id.split_once(':').unwrap().0, "");
    }

    #[tokio::test]
    async fn reset_boundary_buffers_events_while_snapshot_is_built() {
        let hub = EventHub::new();
        let first = hub.publish("one", json!({"n": 1}));
        let (replay, mut live) = hub.replay_and_subscribe(Some("foreign:9"));
        let Replay::Reset { cursor, .. } = replay else {
            panic!("foreign epoch should reset");
        };
        assert_eq!(cursor, first.id);

        // (Text below generated by LLM)
        // Model the events handler awaiting its Status snapshot after the
        // atomic boundary. A concurrent event must remain buffered behind the
        // reset cursor rather than disappear into a subscription gap.
        let publisher = tokio::spawn({
            let hub = hub.clone();
            async move {
                tokio::task::yield_now().await;
                hub.publish("two", json!({"n": 2}))
            }
        });
        tokio::task::yield_now().await;
        let second = publisher.await.unwrap();
        assert_eq!(live.recv().await.unwrap().id, second.id);
    }

    #[tokio::test]
    async fn fresh_subscription_gets_an_atomic_initial_snapshot_boundary() {
        let hub = EventHub::new();
        let first = hub.publish("one", json!({"n": 1}));
        let (replay, mut live) = hub.replay_and_subscribe(None);
        let Replay::Reset { reason, cursor } = replay else {
            panic!("fresh subscription should receive a reset baseline");
        };
        assert_eq!(reason, "initial_snapshot");
        assert_eq!(cursor, first.id);

        // (Text below generated by LLM)
        // Model an instrument event arriving while the HTTP handler awaits its
        // Status query. It must follow the reset rather than fall into a gap.
        let second = hub.publish("two", json!({"n": 2}));
        assert_eq!(live.recv().await.unwrap().id, second.id);
    }

    #[test]
    fn targeted_events_retain_their_transport_audience() {
        let hub = EventHub::new();
        let event = hub.publish_for("owner", "operation", json!({"id": "secret"}));
        assert_eq!(event.audience.as_deref(), Some("owner"));
    }
}
