//! Single-connection managed InstrumentServer actor.

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::{Duration, Instant};

use axum::http::StatusCode;
use chrono::{DateTime, Utc};
use futures::StreamExt;
use qslib_core::com::QSConnection;
use qslib_core::commands::{
    AbortRun, AccessLevel, AccessLevelSet, AccessState, AccessStateQuery, BlockQuery, BlockSet,
    CommandBuilder, ControlZonesQuery, CoverDown, CoverPosition, CoverPositionQuery, DrawerClose,
    DrawerOpen, DrawerStatus, DrawerStatusQuery, ExperimentCollected, ExperimentCompile,
    ExperimentNew, FileMove, MachineStatusQuery, OkParseError, PauseRun, PowerQuery, PowerSet,
    RandomKeyQuery, ReceiveNextResponseError, ReceiveOkResponseError, RemainingTimeQuery,
    RestartSystem, ResumeRun, RunStart, RunStatusQuery, RunningProtocolBodyQuery,
    RunningProtocolMetadataQuery, StatusLedColor, StatusLedMode, StatusLedOff, StatusLedQuery,
    StatusLedSet, StopRun, Subscribe,
};
use qslib_core::parser::{ErrorResponse, LogMessage, OkResponse};
use serde::Serialize;
use serde_json::{json, Value};
use tokio::sync::{mpsc, oneshot, watch};
use tokio_stream::wrappers::BroadcastStream;
use tracing::{debug, info, warn};

use crate::dto::{AccessDto, InstrumentStatusDto, RunStatusDto, RunningProtocolDto};
use crate::error::ServerError;
use crate::events::EventHub;
use qslib_core::protocol::ProtocolDefinition;

const CONNECT_DEADLINE: Duration = Duration::from_secs(10);
const QUERY_DEADLINE: Duration = Duration::from_secs(10);
const CONTROL_DEADLINE: Duration = Duration::from_secs(30);
const INSTRUMENT_EVENT_BUFFER: usize = 4096;

#[derive(Debug, Clone)]
pub struct ServiceConfig {
    pub target: SocketAddr,
    pub password: Option<String>,
    pub max_access: AccessLevel,
    pub queue_capacity: usize,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ServiceHealth {
    pub ready: bool,
    pub generation: u64,
    pub current_access: Option<AccessDto>,
    pub last_successful_command: Option<DateTime<Utc>>,
    pub reconnect_count: u64,
}

#[derive(Debug, Clone)]
pub enum InstrumentOperation {
    Status,
    RunStatus,
    RunningProtocol,
    SetPower(bool),
    SetBlock {
        enabled: bool,
        target_c: Option<f64>,
    },
    SetIndicator {
        color: StatusLedColor,
        mode: StatusLedMode,
    },
    IndicatorOff,
    Drawer {
        open: bool,
        lower_cover: bool,
        verify: bool,
    },
    CoverDown {
        verify: bool,
        ensure_drawer: bool,
    },
    Pause {
        name: Option<String>,
    },
    Resume {
        name: Option<String>,
    },
    Stop {
        name: Option<String>,
    },
    Abort {
        name: Option<String>,
    },
    StartRun(StartRunInput),
    PreflightRun(PreflightRunInput),
    Compile {
        name: String,
        experiments_root: std::path::PathBuf,
        completed_root: std::path::PathBuf,
    },
    DeleteExperiment {
        name: String,
        experiments_root: std::path::PathBuf,
    },
    ReplaceProtocol {
        name: String,
        protocol: ProtocolDefinition,
    },
    GenerateAccessKey,
    Restart,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OverwriteMode {
    False,
    True,
    Incomplete,
}

#[derive(Debug, Clone)]
pub struct StartRunInput {
    pub experiment: String,
    pub overwrite: OverwriteMode,
    pub require_exclusive: bool,
    pub require_drawer_check: bool,
    pub experiments_root: std::path::PathBuf,
    pub completed_root: std::path::PathBuf,
    pub staged: AcceptedPackageSnapshot,
    pub protocol_scpi: String,
    pub protocol_name: String,
    pub sample_volume: f64,
    pub run_mode: String,
}

/// An operation-private copy of the exact package bytes accepted by the HTTP
/// handler. The guard keeps the snapshot alive while a start waits in the
/// server queue, then removes it when the queued operation is discarded or
/// completed.
///
/// (Text above generated by LLM)
#[derive(Debug, Clone)]
pub struct AcceptedPackageSnapshot {
    staged_root: std::path::PathBuf,
    _cleanup: Arc<AcceptedPackageCleanup>,
}

impl AcceptedPackageSnapshot {
    pub fn new(staged_root: std::path::PathBuf, cleanup_root: std::path::PathBuf) -> Self {
        Self {
            staged_root,
            _cleanup: Arc::new(AcceptedPackageCleanup { root: cleanup_root }),
        }
    }

    fn staged_root(&self) -> &std::path::Path {
        &self.staged_root
    }
}

#[derive(Debug)]
struct AcceptedPackageCleanup {
    root: std::path::PathBuf,
}

impl Drop for AcceptedPackageCleanup {
    fn drop(&mut self) {
        if let Err(error) = remove_path_raw(&self.root) {
            warn!(
                path = %self.root.display(),
                %error,
                "could not remove accepted package snapshot"
            );
        }
    }
}

#[derive(Debug, Clone)]
pub struct PreflightRunInput {
    pub experiment: String,
    pub overwrite: OverwriteMode,
    pub experiments_root: std::path::PathBuf,
    pub completed_root: std::path::PathBuf,
}

impl InstrumentOperation {
    fn required_access(&self) -> AccessLevel {
        match self {
            Self::Status | Self::RunStatus | Self::RunningProtocol | Self::PreflightRun(_) => {
                AccessLevel::Observer
            }
            Self::GenerateAccessKey => AccessLevel::Controller,
            Self::Restart => AccessLevel::Controller,
            _ => AccessLevel::Controller,
        }
    }

    fn exclusive(&self) -> bool {
        matches!(
            self,
            Self::Pause { .. } | Self::Resume { .. } | Self::Stop { .. } | Self::Abort { .. }
        ) || matches!(self, Self::StartRun(input) if input.require_exclusive)
    }

    fn read_only(&self) -> bool {
        matches!(
            self,
            Self::Status | Self::RunStatus | Self::RunningProtocol | Self::PreflightRun(_)
        )
    }

    fn deadline(&self) -> Duration {
        match self {
            Self::Status | Self::RunStatus | Self::RunningProtocol | Self::PreflightRun(_) => {
                QUERY_DEADLINE
            }
            Self::StartRun(_) => Duration::from_secs(120),
            Self::Compile { .. } => Duration::from_secs(10 * 60),
            _ => CONTROL_DEADLINE,
        }
    }
}

#[derive(Debug, Clone)]
pub enum InstrumentResult {
    Status(Box<InstrumentStatusDto>),
    RunStatus(RunStatusDto),
    RunningProtocol(RunningProtocolDto),
    AccessKey(String),
    Unit,
}

struct Job {
    operation: InstrumentOperation,
    started: Option<oneshot::Sender<()>>,
    response: oneshot::Sender<Result<InstrumentResult, ServerError>>,
    attempt: u8,
}

pub struct EnqueuedOperation {
    pub started: oneshot::Receiver<()>,
    pub response: oneshot::Receiver<Result<InstrumentResult, ServerError>>,
}

/// Cloneable queue handle. Only the actor task ever owns a [`QSConnection`].
#[derive(Clone)]
pub struct InstrumentService {
    sender: mpsc::Sender<Job>,
    health: watch::Receiver<ServiceHealth>,
    events: EventHub,
    shutdown: watch::Sender<bool>,
}

impl InstrumentService {
    pub fn spawn(config: ServiceConfig, events: EventHub) -> Self {
        let (sender, receiver) = mpsc::channel(config.queue_capacity.max(1));
        let (health_sender, health) = watch::channel(ServiceHealth::default());
        let (shutdown, shutdown_receiver) = watch::channel(false);
        tokio::spawn(run_actor(
            config,
            receiver,
            health_sender,
            events.clone(),
            shutdown_receiver,
        ));
        Self {
            sender,
            health,
            events,
            shutdown,
        }
    }

    pub fn enqueue(
        &self,
        operation: InstrumentOperation,
    ) -> Result<EnqueuedOperation, ServerError> {
        let (started_sender, started) = oneshot::channel();
        let (response, receiver) = oneshot::channel();
        self.sender
            .try_send(Job {
                operation,
                started: Some(started_sender),
                response,
                attempt: 0,
            })
            .map_err(|error| match error {
                mpsc::error::TrySendError::Full(_) => ServerError::queue_full(),
                mpsc::error::TrySendError::Closed(_) => {
                    ServerError::unavailable("instrument service is shutting down")
                }
            })?;
        Ok(EnqueuedOperation {
            started,
            response: receiver,
        })
    }

    pub async fn execute(
        &self,
        operation: InstrumentOperation,
    ) -> Result<InstrumentResult, ServerError> {
        self.enqueue(operation)?
            .response
            .await
            .map_err(|_| ServerError::unavailable("instrument actor dropped the operation"))?
    }

    pub fn health(&self) -> ServiceHealth {
        self.health.borrow().clone()
    }

    pub fn queue_depth(&self) -> usize {
        self.sender.max_capacity() - self.sender.capacity()
    }

    pub fn events(&self) -> &EventHub {
        &self.events
    }

    /// Stop new event streams and notify the actor without waiting for SCPI
    /// cleanup. This is separated from [`Self::shutdown`] so the HTTP server
    /// can stop accepting connections immediately on a process signal.
    ///
    /// (Text above generated by LLM)
    pub fn begin_shutdown(&self) {
        self.events.begin_shutdown();
        let _ = self.shutdown.send(true);
    }

    pub async fn shutdown(&self) {
        self.begin_shutdown();
        let mut health = self.health.clone();
        let _ = tokio::time::timeout(Duration::from_secs(12), async move {
            while health.borrow().ready {
                if health.changed().await.is_err() {
                    break;
                }
            }
        })
        .await;
    }
}

struct ExecutionFailure {
    error: ServerError,
    reconnect: bool,
}

/// Instrument state captured at the time a subscription message is received.
///
/// Keeping this beside the managed connection makes every persisted SSE event
/// self-contained. In particular, replay consumers must not query a current
/// (possibly idle) status snapshot to interpret an older Run/Temperature event.
///
/// (Text above generated by LLM)
#[derive(Debug, Clone, Default, PartialEq, Serialize)]
struct InstrumentEventContext {
    run_name: Option<String>,
    zone_targets_c: Vec<f64>,
    stage: Option<i64>,
    cycle: Option<i64>,
    step: Option<i64>,
}

impl InstrumentEventContext {
    fn from_status(status: Option<&InstrumentStatusDto>) -> Self {
        let Some(status) = status else {
            return Self::default();
        };
        let zone_targets_c = (1..=status.zone_count)
            .map(|zone| {
                let expected = format!("Zone{zone}");
                status
                    .target_temperatures_c
                    .get(&expected)
                    .copied()
                    .or_else(|| {
                        status
                            .target_temperatures_c
                            .iter()
                            .find(|(name, _)| name.eq_ignore_ascii_case(&expected))
                            .map(|(_, target)| *target)
                    })
                    .unwrap_or_default()
            })
            .collect();
        Self {
            run_name: (status.run.name != "-" && !status.run.name.is_empty())
                .then(|| status.run.name.clone()),
            zone_targets_c,
            stage: nonnegative(status.run.stage),
            cycle: nonnegative(status.run.cycle),
            step: nonnegative(status.run.step),
        }
    }

    /// Update context before serializing the event. Returns true for a run
    /// terminal: that event carries the final context and later events do not.
    ///
    /// (Text above generated by LLM)
    fn observe(&mut self, topic: &str, message: &str) -> bool {
        if !topic.eq_ignore_ascii_case("Run") {
            return false;
        }

        let mut parts = message.trim().splitn(2, char::is_whitespace);
        let action = parts.next().unwrap_or_default();
        let content = parts
            .next()
            .and_then(|rest| OkResponse::try_from(rest.trim()).ok());

        if action.eq_ignore_ascii_case("Starting") {
            self.run_name = content
                .as_ref()
                .and_then(|content| content.args.first())
                .and_then(scpi_string)
                .filter(|name| name != "-" && !name.is_empty());
            self.stage = None;
            self.cycle = None;
            self.step = None;
        } else if let Some(run_name) = content
            .as_ref()
            .and_then(|content| content.options.get("run"))
            .and_then(scpi_string)
            .filter(|name| name != "-" && !name.is_empty())
        {
            // (Text below generated by LLM)
            // Collected messages include -run, so they remain interpretable
            // even when Starting has fallen out of the replay window.
            self.run_name = Some(run_name);
        }

        if action.eq_ignore_ascii_case("Stage") {
            let observed_stage = content
                .as_ref()
                .and_then(|content| content.args.first())
                .and_then(scpi_string)
                .and_then(|stage| parse_stage(&stage));
            // (Text below generated by LLM)
            // POSTRun has no numeric position in the log message. Preserve
            // the last known stage rather than erasing useful event-time
            // context; a numeric Stage/StageN or PRERUN still replaces it.
            if observed_stage.is_some()
                || !content.as_ref().is_some_and(|content| {
                    content.args.first().is_some_and(|stage| {
                        scpi_string(stage)
                            .is_some_and(|stage| stage.eq_ignore_ascii_case("POSTRun"))
                    })
                })
            {
                self.stage = observed_stage;
            }
            self.cycle = None;
            self.step = None;
        } else if action.eq_ignore_ascii_case("Cycle") {
            self.cycle = content
                .as_ref()
                .and_then(|content| content.args.first())
                .and_then(scpi_i64);
            self.step = None;
        } else if action.eq_ignore_ascii_case("Step") {
            self.step = content
                .as_ref()
                .and_then(|content| content.args.first())
                .and_then(scpi_i64);
        } else if action.eq_ignore_ascii_case("Collected") {
            if let Some(content) = content.as_ref() {
                self.stage = content.options.get("stage").and_then(scpi_i64);
                self.cycle = content.options.get("cycle").and_then(scpi_i64);
                self.step = content.options.get("step").and_then(scpi_i64);
            }
        } else if action.eq_ignore_ascii_case("Ramping") {
            self.observe_ramping(content.as_ref());
        }

        ["Ended", "Aborted", "Stopped"]
            .iter()
            .any(|terminal| action.eq_ignore_ascii_case(terminal))
    }

    fn observe_ramping(&mut self, content: Option<&OkResponse>) {
        let Some(content) = content else { return };
        let Some(zones) = content.options.get("zones").map(ToString::to_string) else {
            return;
        };
        let Some(targets) = content.options.get("targets").map(ToString::to_string) else {
            return;
        };
        for (zone, target) in zones.split(',').zip(targets.split(',')) {
            let zone = zone.trim();
            if zone.eq_ignore_ascii_case("Cover") {
                continue;
            }
            let zone = zone
                .get(..4)
                .filter(|prefix| prefix.eq_ignore_ascii_case("Zone"))
                .map_or(zone, |_| &zone[4..]);
            let Ok(zone) = zone.parse::<usize>() else {
                continue;
            };
            let Ok(target) = target.trim().parse::<f64>() else {
                continue;
            };
            // (Text below generated by LLM)
            // Six zones are usual. The bound prevents malformed instrument
            // messages from causing unbounded allocation while allowing future
            // higher-zone instruments to preserve their event context.
            if zone == 0 || zone > 96 || !target.is_finite() {
                continue;
            }
            if self.zone_targets_c.len() < zone {
                self.zone_targets_c.resize(zone, 0.0);
            }
            self.zone_targets_c[zone - 1] = target;
        }
    }

    fn clear_run(&mut self) {
        self.run_name = None;
        self.stage = None;
        self.cycle = None;
        self.step = None;
    }
}

fn nonnegative(value: i64) -> Option<i64> {
    (value >= 0).then_some(value)
}

fn scpi_string(value: &qslib_core::parser::Value) -> Option<String> {
    value.clone().try_into_string().ok()
}

fn scpi_i64(value: &qslib_core::parser::Value) -> Option<i64> {
    value
        .clone()
        .try_into_i64()
        .ok()
        .or_else(|| value.to_string().parse().ok())
}

fn parse_stage(value: &str) -> Option<i64> {
    if value.eq_ignore_ascii_case("PRERUN") {
        return Some(0);
    }
    value.parse().ok().or_else(|| {
        value
            .get(..5)
            .filter(|prefix| prefix.eq_ignore_ascii_case("Stage"))
            .and_then(|_| value[5..].parse().ok())
    })
}

fn publish_instrument_event(
    events: &EventHub,
    context: &mut InstrumentEventContext,
    message: LogMessage,
) {
    let topic = message.topic.clone();
    let terminal = context.observe(&topic, &message.message);
    events.publish(
        topic.to_ascii_lowercase(),
        json!({
            "instrument_timestamp": message.timestamp,
            "message": message.message,
            "context": context,
        }),
    );
    if terminal {
        context.clear_run();
    }
}

impl ExecutionFailure {
    fn transport(message: impl Into<String>) -> Self {
        Self {
            // (Text below generated by LLM)
            // A transport failure may follow a fully submitted SCPI command;
            // without its response the mutation outcome cannot be inferred.
            error: ServerError::unavailable(message).outcome("unknown"),
            reconnect: true,
        }
    }

    fn without_reconnect(error: ServerError) -> Self {
        Self {
            error,
            reconnect: false,
        }
    }
}

async fn run_actor(
    config: ServiceConfig,
    mut jobs: mpsc::Receiver<Job>,
    health_sender: watch::Sender<ServiceHealth>,
    events: EventHub,
    mut shutdown: watch::Receiver<bool>,
) {
    let mut health = ServiceHealth::default();
    let mut backoff = Duration::from_millis(250);
    let mut pending: Option<Job> = None;

    loop {
        if *shutdown.borrow() {
            return;
        }
        let (connection, mut subscriptions) = match connect_and_initialize(&config).await {
            Ok(connection) => connection,
            Err(error) => {
                health.ready = false;
                health.current_access = None;
                let _ = health_sender.send(health.clone());
                warn!("managed SCPI connect failed: {error}");
                tokio::select! {
                    _ = tokio::time::sleep(jitter(backoff, health.reconnect_count)) => {},
                    job = jobs.recv(), if pending.is_none() => {
                        let Some(job) = job else { return };
                        pending = Some(job);
                    }
                    changed = shutdown.changed() => {
                        if changed.is_err() || *shutdown.borrow() {
                            return;
                        }
                    }
                }
                backoff = (backoff * 2).min(Duration::from_secs(30));
                health.reconnect_count += 1;
                continue;
            }
        };

        backoff = Duration::from_millis(250);
        health.ready = true;
        health.generation += 1;
        health.current_access = Some(AccessDto {
            level: "observer".to_string(),
            exclusive: false,
            stealth: false,
        });
        let _ = health_sender.send(health.clone());
        info!(
            generation = health.generation,
            "managed SCPI connection ready"
        );

        let reset_snapshot = fetch_status(&connection).await.ok();
        let mut event_context = InstrumentEventContext::from_status(reset_snapshot.as_ref());
        events.publish(
            "reset",
            json!({
                "generation": health.generation,
                "connected": true,
                "status": reset_snapshot,
                "context": &event_context,
            }),
        );

        let mut status_cache: Option<(Instant, InstrumentStatusDto)> =
            reset_snapshot.map(|status| (Instant::now(), status));
        let mut reconnect = false;

        while !reconnect {
            let next_job = async {
                if pending.is_some() {
                    pending.take()
                } else {
                    jobs.recv().await
                }
            };
            tokio::select! {
                job = next_job => {
                    let Some(mut job) = job else {
                        shutdown_connection(connection, &mut health, &health_sender).await;
                        return;
                    };
                    // (Text below generated by LLM)
                    // A disconnected synchronous HTTP caller drops its
                    // response receiver. Do not execute a stale queued control
                    // after the caller can no longer observe its outcome.
                    if job.response.is_closed() {
                        continue;
                    }
                    if let Some(started) = job.started.take() {
                        let _ = started.send(());
                    }
                    let mut subscription_failed = false;
                    let mut drain_subscriptions = true;
                    let result = {
                        let execution = execute_operation(
                            &connection,
                            &config,
                            &job.operation,
                            &mut health,
                            &health_sender,
                            &mut status_cache,
                        );
                        tokio::pin!(execution);
                        loop {
                            tokio::select! {
                                biased;
                                changed = shutdown.changed() => {
                                    if changed.is_err() || *shutdown.borrow() {
                                        break None;
                                    }
                                }
                                result = &mut execution => break Some(result),
                                subscription = subscriptions.next(), if drain_subscriptions => {
                                    match subscription {
                                        Some(Ok(message)) => {
                                            publish_instrument_event(
                                                &events,
                                                &mut event_context,
                                                message,
                                            );
                                        }
                                        Some(Err(_lagged)) => {
                                            // (Text below generated by LLM)
                                            // Continue draining what remains, then reconnect
                                            // after the operation outcome is known so a reset
                                            // snapshot repairs the lost subscription history.
                                            subscription_failed = true;
                                        }
                                        None => {
                                            subscription_failed = true;
                                            drain_subscriptions = false;
                                        }
                                    }
                                }
                            }
                        }
                    };
                    let Some(result) = result else {
                        let _ = job.response.send(Err(
                            ServerError::unavailable("instrument service is shutting down")
                                .outcome("unknown")
                        ));
                        shutdown_connection(connection, &mut health, &health_sender).await;
                        return;
                    };
                    match result {
                        Ok(value) => {
                            health.last_successful_command = Some(Utc::now());
                            let _ = health_sender.send(health.clone());
                            let _ = job.response.send(Ok(value));
                        }
                        Err(failure) if failure.reconnect && job.operation.read_only() && job.attempt == 0 => {
                            job.attempt = 1;
                            pending = Some(job);
                            reconnect = true;
                        }
                        Err(failure) => {
                            let _ = job.response.send(Err(failure.error));
                            reconnect = failure.reconnect;
                        }
                    }
                    reconnect |= subscription_failed;
                }
                subscription = subscriptions.next() => {
                    match subscription {
                        Some(Ok(message)) => {
                            publish_instrument_event(
                                &events,
                                &mut event_context,
                                message,
                            );
                        }
                        Some(Err(_lagged)) => {
                            reconnect = true;
                        }
                        None => reconnect = true,
                    }
                }
                _ = tokio::time::sleep(Duration::from_secs(1)) => {
                    if !connection.is_connected().await {
                        reconnect = true;
                    }
                }
                changed = shutdown.changed() => {
                    if changed.is_err() || *shutdown.borrow() {
                        shutdown_connection(connection, &mut health, &health_sender).await;
                        return;
                    }
                }
            }
        }

        health.ready = false;
        health.current_access = None;
        let _ = health_sender.send(health.clone());
        events.publish(
            "connection",
            json!({"generation": health.generation, "connected": false}),
        );
        connection.close().await;
        health.reconnect_count += 1;
    }
}

async fn connect_and_initialize(
    config: &ServiceConfig,
) -> Result<(QSConnection, BroadcastStream<LogMessage>), String> {
    if config.max_access < AccessLevel::Observer {
        return Err("--max-access must permit Observer".to_string());
    }
    let host = config.target.ip().to_string();
    let connection = tokio::time::timeout(
        CONNECT_DEADLINE,
        QSConnection::connect_tcp(&host, config.target.port()),
    )
    .await
    .map_err(|_| "greeting deadline exceeded".to_string())?
    .map_err(|error| error.to_string())?;

    let access_result = match config.password.as_deref() {
        Some(password) => {
            connection
                .authenticate_and_set_access_level(password, AccessLevel::Observer)
                .await
        }
        None => connection.set_access_level(AccessLevel::Observer).await,
    };
    access_result.map_err(|error| format!("failed to establish Observer access: {error}"))?;
    let access: AccessState = run_command(&connection, AccessStateQuery, QUERY_DEADLINE)
        .await
        .map_err(|failure| failure.error.message)?;
    if access.level != AccessLevel::Observer || access.exclusive || access.stealth {
        connection.close().await;
        return Err(format!(
            "unexpected access tuple after initialization: {access:?}"
        ));
    }

    // (Text below generated by LLM)
    // Install one local wildcard receiver before enabling remote topics. The
    // wildcard is local-only (never sent to InstrumentServer), preserves wire
    // order across topics, and closes the post-SUBS/pre-receiver loss window.
    let subscriptions = subscription_stream(&connection);
    run_command(
        &connection,
        Subscribe::topics(&["Temperature", "Time", "Run", "Error", "LEDStatus"])
            .with_timestamp(true),
        QUERY_DEADLINE,
    )
    .await
    .map_err(|failure| failure.error.message)?;
    Ok((connection, subscriptions))
}

async fn execute_operation(
    connection: &QSConnection,
    config: &ServiceConfig,
    operation: &InstrumentOperation,
    health: &mut ServiceHealth,
    health_sender: &watch::Sender<ServiceHealth>,
    status_cache: &mut Option<(Instant, InstrumentStatusDto)>,
) -> Result<InstrumentResult, ExecutionFailure> {
    let required = operation.required_access();
    if required > config.max_access {
        return Err(ExecutionFailure::without_reconnect(ServerError::forbidden(
            format!(
                "operation requires {} access, above configured cap {}",
                String::from(required),
                String::from(config.max_access.clone())
            ),
        )));
    }

    if required > AccessLevel::Observer {
        set_and_verify_access(connection, required.clone(), operation.exclusive()).await?;
        health.current_access = Some(AccessDto {
            level: String::from(required.clone()).to_ascii_lowercase(),
            exclusive: operation.exclusive(),
            stealth: false,
        });
        let _ = health_sender.send(health.clone());
    }

    let result: Result<InstrumentResult, ExecutionFailure> =
        match tokio::time::timeout(operation.deadline(), async {
            match operation {
                InstrumentOperation::Status => {
                    // Explicit status requests always reflect a fresh SCPI
                    // observation. The cached snapshot is retained only for
                    // event/reset bookkeeping, never as a public query result.
                    let status = fetch_status(connection).await?;
                    *status_cache = Some((Instant::now(), status.clone()));
                    Ok(InstrumentResult::Status(Box::new(status)))
                }
                InstrumentOperation::RunStatus => {
                    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
                    let remaining = fetch_remaining_time(connection).await?;
                    Ok(InstrumentResult::RunStatus(RunStatusDto::from_parts(
                        status, remaining,
                    )))
                }
                InstrumentOperation::RunningProtocol => {
                    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
                    if status.name == "-" || status.state.eq_ignore_ascii_case("IDLE") {
                        return Err(ExecutionFailure::without_reconnect(ServerError::not_found(
                            "no protocol is currently running",
                        )));
                    }
                    let metadata =
                        run_command(connection, RunningProtocolMetadataQuery, QUERY_DEADLINE)
                            .await?;
                    let body = run_command(connection, RunningProtocolBodyQuery, QUERY_DEADLINE)
                        .await?
                        .0;
                    let scpi = format!(
                        "PROT -volume={} -runmode={} {} {}",
                        metadata.sample_volume,
                        metadata.run_mode,
                        shell_words::quote(&metadata.name),
                        body
                    );
                    Ok(InstrumentResult::RunningProtocol(RunningProtocolDto {
                        name: metadata.name,
                        sample_volume: metadata.sample_volume,
                        run_mode: metadata.run_mode,
                        scpi,
                    }))
                }
                InstrumentOperation::SetPower(enabled) => {
                    run_command(
                        connection,
                        if *enabled {
                            PowerSet::on()
                        } else {
                            PowerSet::off()
                        },
                        operation.deadline(),
                    )
                    .await?;
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::SetBlock { enabled, target_c } => {
                    run_command(
                        connection,
                        BlockSet {
                            enabled: *enabled,
                            target_c: *target_c,
                        },
                        operation.deadline(),
                    )
                    .await?;
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::SetIndicator { color, mode } => {
                    run_command(
                        connection,
                        StatusLedSet::new(*color, *mode),
                        operation.deadline(),
                    )
                    .await?;
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::IndicatorOff => {
                    run_command(connection, StatusLedOff, operation.deadline()).await?;
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Drawer {
                    open,
                    lower_cover,
                    verify,
                } => {
                    if *open {
                        run_command(connection, DrawerOpen, operation.deadline()).await?;
                    } else {
                        run_command(connection, DrawerClose, operation.deadline()).await?;
                        if *lower_cover {
                            run_command(connection, CoverDown, operation.deadline()).await?;
                        }
                    }
                    if *verify {
                        let drawer =
                            run_command(connection, DrawerStatusQuery, QUERY_DEADLINE).await?;
                        let expected = if *open {
                            DrawerStatus::Open
                        } else {
                            DrawerStatus::Closed
                        };
                        if drawer != expected {
                            return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                                format!(
                            "drawer verification failed: expected {expected:?}, got {drawer:?}"
                        ),
                            )));
                        }
                        if !*open && *lower_cover {
                            let cover =
                                run_command(connection, CoverPositionQuery, QUERY_DEADLINE).await?;
                            if cover != CoverPosition::Down {
                                return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                                    format!(
                                        "cover verification failed: expected down, got {cover:?}"
                                    ),
                                )));
                            }
                        }
                    }
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::CoverDown {
                    verify,
                    ensure_drawer,
                } => {
                    if *ensure_drawer {
                        let drawer =
                            run_command(connection, DrawerStatusQuery, QUERY_DEADLINE).await?;
                        if matches!(drawer, DrawerStatus::Open | DrawerStatus::Unknown) {
                            run_command(connection, DrawerClose, operation.deadline()).await?;
                        }
                    }
                    run_command(connection, CoverDown, operation.deadline()).await?;
                    if *verify {
                        if *ensure_drawer {
                            let drawer =
                                run_command(connection, DrawerStatusQuery, QUERY_DEADLINE).await?;
                            if drawer != DrawerStatus::Closed {
                                return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                                    format!(
                                        "drawer verification failed: expected closed, got {drawer:?}"
                                    ),
                                )));
                            }
                        }
                        let cover =
                            run_command(connection, CoverPositionQuery, QUERY_DEADLINE).await?;
                        if cover != CoverPosition::Down {
                            return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                                format!("cover verification failed: expected down, got {cover:?}"),
                            )));
                        }
                    }
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Pause { name } => {
                    verify_requested_run(connection, name.as_deref()).await?;
                    run_ack_command(connection, PauseRun, operation.deadline()).await?;
                    verify_run_state(connection, name.as_deref(), |state| state.contains("PAUS"))
                        .await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Resume { name } => {
                    verify_requested_run(connection, name.as_deref()).await?;
                    run_ack_command(connection, ResumeRun, operation.deadline()).await?;
                    verify_run_state(connection, name.as_deref(), |state| !state.contains("PAUS"))
                        .await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Stop { name } => {
                    let actual = verify_requested_run(connection, name.as_deref()).await?;
                    run_ack_command(connection, StopRun(actual), operation.deadline()).await?;
                    verify_run_state(connection, name.as_deref(), |state| {
                        state.contains("STOP") || state == "IDLE"
                    })
                    .await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Abort { name } => {
                    let actual = verify_requested_run(connection, name.as_deref()).await?;
                    run_ack_command(connection, AbortRun(actual), operation.deadline()).await?;
                    verify_run_state(connection, name.as_deref(), |state| {
                        state == "IDLE" || state.contains("TERM")
                    })
                    .await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::StartRun(input) => {
                    start_run(connection, input, operation.deadline()).await?;
                    *status_cache = None;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::PreflightRun(input) => {
                    preflight_run(connection, input).await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::Compile {
                    name,
                    experiments_root,
                    completed_root,
                } => {
                    let working = experiments_root.join(name);
                    if !working.is_dir() {
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::NOT_FOUND,
                                "run_not_found",
                                "working run not found",
                            )
                            .details(json!({"name": name})),
                        ));
                    }
                    let attributes = crate::file::read_attributes(&working)
                        .map_err(ExecutionFailure::without_reconnect)?;
                    if !attributes.contains_key("run") {
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::NOT_FOUND,
                                "run_not_found",
                                "working directory is not marked as a run",
                            )
                            .details(json!({"name": name, "attributes": attributes})),
                        ));
                    }
                    let finished = attributes
                        .get("state")
                        .and_then(Value::as_str)
                        .is_some_and(|state| {
                            state.eq_ignore_ascii_case("Completed")
                                || state.eq_ignore_ascii_case("Terminated")
                        });
                    if !finished {
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::CONFLICT,
                                "run_not_finished",
                                "run state is not Completed or Terminated",
                            )
                            .details(json!({"name": name, "attributes": attributes})),
                        ));
                    }
                    let collected = attributes.get("collected").is_some_and(|value| match value {
                        Value::Bool(value) => *value,
                        Value::String(value) => value.eq_ignore_ascii_case("true"),
                        _ => false,
                    });
                    if collected {
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::CONFLICT,
                                "already_collected",
                                "run has already been collected",
                            )
                            .details(json!({"name": name, "attributes": attributes})),
                        ));
                    }
                    let generated = experiments_root.join(format!("{name}.eds"));
                    let completed = completed_root.join(format!("{name}.eds"));
                    if completed.exists() {
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::CONFLICT,
                                "completed_exists",
                                "completed EDS already exists",
                            )
                            .details(json!({"name": name})),
                        ));
                    }

                    // (Text below generated by LLM)
                    // A previous failed/timed-out compilation may have left an EDS at
                    // the output path. Quarantine it before submitting EXP:RUN so the
                    // poll below can only observe an artifact created after this
                    // operation was accepted.
                    let generated_backup = experiments_root.join(format!(
                        ".{name}.{}.eds.qslib-compile-backup",
                        uuid::Uuid::new_v4()
                    ));
                    if path_present(&generated).map_err(|error| {
                        ExecutionFailure::without_reconnect(ServerError::internal(format!(
                            "failed to inspect generated EDS before compilation: {error}"
                        )))
                    })? {
                        std::fs::rename(&generated, &generated_backup).map_err(|error| {
                            ExecutionFailure::without_reconnect(ServerError::internal(format!(
                                "failed to quarantine preexisting generated EDS: {error}"
                            )))
                        })?;
                    }

                    let mut possibly_accepted = false;
                    let compile_result: Result<(), ExecutionFailure> = async {
                        // (Text below generated by LLM)
                        // EXP:RUN returns NEXT when compilation is accepted. Release
                        // Controller while InstrumentServer performs the long-running
                        // ZIP and poll without interleaving another server operation.
                        run_ack_command_tracking_submission(
                            connection,
                            ExperimentCompile { name: name.clone() },
                            CONTROL_DEADLINE,
                            &mut possibly_accepted,
                        )
                        .await?;
                        set_and_verify_access(connection, AccessLevel::Observer, false).await?;
                        health.current_access = Some(AccessDto {
                            level: "observer".to_string(),
                            exclusive: false,
                            stealth: false,
                        });
                        let _ = health_sender.send(health.clone());

                        let compile_deadline = Instant::now() + operation.deadline();
                        while !generated.is_file() {
                            if Instant::now() >= compile_deadline {
                                return Err(ExecutionFailure::without_reconnect(
                                    ServerError::timeout("EDS compilation deadline exceeded")
                                        .outcome("unknown"),
                                ));
                            }
                            tokio::time::sleep(Duration::from_millis(500)).await;
                        }

                        set_and_verify_access(connection, AccessLevel::Controller, false).await?;
                        health.current_access = Some(AccessDto {
                            level: "controller".to_string(),
                            exclusive: false,
                            stealth: false,
                        });
                        let _ = health_sender.send(health.clone());
                        run_command(
                            connection,
                            FileMove {
                                source: format!("experiments:{name}.eds"),
                                destination: format!("public_run_complete:{name}.eds"),
                            },
                            CONTROL_DEADLINE,
                        )
                        .await?;
                        run_command(
                            connection,
                            ExperimentCollected { name: name.clone() },
                            CONTROL_DEADLINE,
                        )
                        .await?;
                        Ok(())
                    }
                    .await;

                    match compile_result {
                        Ok(()) => match remove_path_raw(&generated_backup) {
                            Ok(()) => Ok(InstrumentResult::Unit),
                            Err(error) => Err(filesystem_failure(
                                "EDS compilation succeeded but stale-artifact cleanup was incomplete",
                                vec![format!(
                                    "failed to remove quarantined generated EDS: {error}"
                                )],
                                [&generated_backup],
                                None,
                            )),
                        },
                        Err(mut failure) if possibly_accepted => {
                            failure.error.outcome = "unknown";
                            add_preserved_paths(
                                &mut failure.error,
                                "EDS compilation may have been accepted; the preexisting artifact remains quarantined",
                                [&generated_backup],
                            );
                            Err(failure)
                        }
                        Err(failure) => {
                            if !path_present(&generated_backup).unwrap_or(true) {
                                return Err(failure);
                            }
                            if path_present(&generated).unwrap_or(true) {
                                return Err(filesystem_failure(
                                    "EDS compilation was rejected but the output path changed before rollback",
                                    vec![
                                        "refusing to overwrite the unexpected generated EDS"
                                            .to_string(),
                                    ],
                                    [&generated_backup, &generated],
                                    Some(failure),
                                ));
                            }
                            match restore_path_checked(&generated_backup, &generated) {
                                Ok(()) => Err(failure),
                                Err(error) => Err(filesystem_failure(
                                    "EDS compilation was rejected and stale-artifact restoration was incomplete",
                                    vec![error],
                                    [&generated_backup, &generated],
                                    Some(failure),
                                )),
                            }
                        }
                    }
                }
                InstrumentOperation::DeleteExperiment {
                    name,
                    experiments_root,
                } => {
                    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
                    if status.name == *name && !status.state.eq_ignore_ascii_case("IDLE") {
                        return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                            "cannot delete the current run",
                        )));
                    }
                    let working = experiments_root.join(name);
                    let staged = experiments_root.join(".qslib-staging").join(name);
                    if !working.exists() && !staged.exists() {
                        return Err(ExecutionFailure::without_reconnect(ServerError::not_found(
                            "experiment not found",
                        )));
                    }
                    remove_path_checked(&working)?;
                    remove_path_checked(&staged)?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::ReplaceProtocol { name, protocol } => {
                    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
                    if status.name != *name || status.state.eq_ignore_ascii_case("IDLE") {
                        let current_name = status.name.clone();
                        return Err(ExecutionFailure::without_reconnect(
                            ServerError::coded(
                                StatusCode::CONFLICT,
                                "not_running",
                                format!("current run is {:?}, not {:?}", current_name, name),
                            )
                            .details(json!({
                                "requested": name,
                                "current": RunStatusDto::from(status),
                            })),
                        ));
                    }
                    run_command(connection, protocol.clone(), operation.deadline()).await?;
                    Ok(InstrumentResult::Unit)
                }
                InstrumentOperation::GenerateAccessKey => {
                    let key = run_command(connection, RandomKeyQuery, operation.deadline()).await?;
                    Ok(InstrumentResult::AccessKey(key.0))
                }
                InstrumentOperation::Restart => {
                    run_ack_command(connection, RestartSystem, operation.deadline()).await?;
                    Ok(InstrumentResult::Unit)
                }
            }
        })
        .await
        {
            Ok(result) => result,
            Err(_) => Err(ExecutionFailure {
                error: ServerError::timeout("server operation deadline exceeded"),
                reconnect: true,
            }),
        };

    if required > AccessLevel::Observer {
        if let Err(failure) = set_and_verify_access(connection, AccessLevel::Observer, false).await
        {
            return Err(ExecutionFailure {
                error: ServerError::unavailable(format!(
                    "operation finished but Observer access restoration failed: {}",
                    failure.error.message
                ))
                .outcome("unknown"),
                reconnect: true,
            });
        }
        health.current_access = Some(AccessDto {
            level: "observer".to_string(),
            exclusive: false,
            stealth: false,
        });
        let _ = health_sender.send(health.clone());
    }
    result
}

async fn start_run(
    connection: &QSConnection,
    input: &StartRunInput,
    deadline: Duration,
) -> Result<(), ExecutionFailure> {
    preflight_run(
        connection,
        &PreflightRunInput {
            experiment: input.experiment.clone(),
            overwrite: input.overwrite,
            experiments_root: input.experiments_root.clone(),
            completed_root: input.completed_root.clone(),
        },
    )
    .await?;

    let working = input.experiments_root.join(&input.experiment);
    let completed = input
        .completed_root
        .join(format!("{}.eds", input.experiment));

    let suffix = uuid::Uuid::new_v4();
    let working_backup = input
        .experiments_root
        .join(format!(".{}.{}.qslib-backup", input.experiment, suffix));
    let completed_backup = input
        .completed_root
        .join(format!(".{}.{}.eds.qslib-backup", input.experiment, suffix));
    if working.exists() {
        std::fs::rename(&working, &working_backup).map_err(|error| {
            ExecutionFailure::without_reconnect(ServerError::internal(format!(
                "failed to back up working experiment: {error}"
            )))
        })?;
    }
    if completed.exists() {
        if let Err(error) = std::fs::rename(&completed, &completed_backup) {
            let failure = ExecutionFailure::without_reconnect(ServerError::internal(format!(
                "failed to back up completed run: {error}"
            )));
            if let Err(restore_error) = restore_path_checked(&working_backup, &working) {
                return Err(filesystem_failure(
                    "completed-run backup failed and working-experiment restoration was incomplete",
                    vec![format!(
                        "failed to restore working experiment backup: {restore_error}"
                    )],
                    [&working_backup, &completed_backup],
                    Some(failure),
                ));
            }
            return Err(failure);
        }
    }

    let mut possibly_accepted = false;
    let result: Result<(), ExecutionFailure> = async {
        run_command(connection, PowerSet::on(), deadline).await?;
        run_command(connection, DrawerClose, deadline).await?;
        run_command(connection, CoverDown, deadline).await?;
        if input.require_drawer_check {
            let drawer = run_command(connection, DrawerStatusQuery, QUERY_DEADLINE).await?;
            let cover = run_command(connection, CoverPositionQuery, QUERY_DEADLINE).await?;
            if drawer != DrawerStatus::Closed || cover != CoverPosition::Down {
                return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                    format!("drawer/cover verification failed ({drawer:?}, {cover:?})"),
                )));
            }
        }
        run_command(
            connection,
            ExperimentNew {
                name: input.experiment.clone(),
                template: "ruo".to_string(),
            },
            deadline,
        )
        .await?;
        merge_staged_experiment(&working, input.staged.staged_root())
            .map_err(ExecutionFailure::without_reconnect)?;
        let protocol = ProtocolDefinition::new(input.protocol_scpi.clone()).map_err(|error| {
            ExecutionFailure::without_reconnect(ServerError::bad_request(format!(
                "invalid staged QSLib protocol: {error}"
            )))
        })?;
        run_command(connection, protocol, deadline).await?;
        run_ack_command_tracking_submission(
            connection,
            RunStart {
                sample_volume: input.sample_volume,
                run_mode: input.run_mode.clone(),
                protocol: input.protocol_name.clone(),
                experiment: input.experiment.clone(),
            },
            deadline,
            &mut possibly_accepted,
        )
        .await?;
        let verification_deadline = Instant::now() + deadline;
        loop {
            let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
            if status.name == input.experiment && !status.state.eq_ignore_ascii_case("IDLE") {
                break;
            }
            if Instant::now() >= verification_deadline {
                return Err(ExecutionFailure::without_reconnect(
                    ServerError::timeout(format!(
                        "run start was accepted but current run did not become {:?}",
                        input.experiment
                    ))
                    .outcome("unknown"),
                ));
            }
            tokio::time::sleep(Duration::from_millis(200)).await;
        }
        Ok(())
    }
    .await;

    match result {
        Ok(()) => {
            let cleanup_errors = remove_paths_checked([
                (&working_backup, "working experiment backup"),
                (&completed_backup, "completed run backup"),
            ]);
            if cleanup_errors.is_empty() {
                Ok(())
            } else {
                Err(filesystem_failure(
                    "run start succeeded but backup cleanup was incomplete",
                    cleanup_errors,
                    [&working_backup, &completed_backup],
                    None,
                ))
            }
        }
        Err(mut failure) if possibly_accepted => {
            failure.error.outcome = "unknown";
            add_preserved_paths(
                &mut failure.error,
                "run start may have been accepted; filesystem rollback was not attempted",
                [&working_backup, &completed_backup],
            );
            Err(failure)
        }
        Err(failure) => {
            let mut rollback_errors = Vec::new();
            match remove_path_raw(&working) {
                Ok(()) => {
                    if let Err(error) = restore_path_checked(&working_backup, &working) {
                        rollback_errors.push(format!(
                            "failed to restore working experiment backup: {error}"
                        ));
                    }
                }
                Err(error) => rollback_errors.push(format!(
                    "failed to remove newly-created working experiment: {error}"
                )),
            }
            if let Err(error) = restore_path_checked(&completed_backup, &completed) {
                rollback_errors.push(format!("failed to restore completed run backup: {error}"));
            }
            if rollback_errors.is_empty() {
                Err(failure)
            } else {
                Err(filesystem_failure(
                    "run start failed and filesystem rollback was incomplete",
                    rollback_errors,
                    [&working_backup, &completed_backup],
                    Some(failure),
                ))
            }
        }
    }
}

async fn preflight_run(
    connection: &QSConnection,
    input: &PreflightRunInput,
) -> Result<(), ExecutionFailure> {
    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
    if !status.state.eq_ignore_ascii_case("IDLE") {
        return Err(ExecutionFailure::without_reconnect(
            ServerError::coded(
                StatusCode::CONFLICT,
                "machine_busy",
                format!("instrument is not idle (state {})", status.state),
            )
            .details(json!({"current": RunStatusDto::from(status)})),
        ));
    }

    if input.experiments_root.join(&input.experiment).exists()
        && input.overwrite == OverwriteMode::False
    {
        return Err(ExecutionFailure::without_reconnect(
            ServerError::coded(
                StatusCode::CONFLICT,
                "working_exists",
                "working experiment already exists",
            )
            .details(json!({"name": input.experiment})),
        ));
    }
    if input
        .completed_root
        .join(format!("{}.eds", input.experiment))
        .exists()
        && input.overwrite != OverwriteMode::True
    {
        return Err(ExecutionFailure::without_reconnect(
            ServerError::coded(
                StatusCode::CONFLICT,
                "completed_exists",
                "completed run already exists",
            )
            .details(json!({"name": input.experiment})),
        ));
    }
    Ok(())
}

fn merge_staged_experiment(
    target: &std::path::Path,
    staged: &std::path::Path,
) -> Result<(), ServerError> {
    let parent = target
        .parent()
        .ok_or_else(|| ServerError::internal("working experiment has no parent"))?;
    let merged = parent.join(format!(".qslib-merge-{}", uuid::Uuid::new_v4()));
    copy_tree(target, &merged, false)?;
    if let Err(error) = copy_tree(staged, &merged, true) {
        return match remove_path_raw(&merged) {
            Ok(()) => Err(error),
            Err(cleanup_error) => Err(ServerError::internal(format!(
                "{}; failed to remove incomplete merge tree {}: {cleanup_error}",
                error.message,
                merged.display()
            ))
            .outcome("unknown")
            .details(json!({"preserved_paths": [merged.display().to_string()]}))),
        };
    }
    for metadata in [".qslib-package.zip", ".qslib-package.etag"] {
        remove_path_raw(&merged.join(metadata)).map_err(|error| {
            ServerError::internal(format!(
                "failed to remove staging metadata from merged experiment: {error}"
            ))
            .outcome("unknown")
            .details(json!({"preserved_paths": [merged.display().to_string()]}))
        })?;
    }
    let generated = parent.join(format!(".qslib-generated-{}", uuid::Uuid::new_v4()));
    std::fs::rename(target, &generated).map_err(|error| {
        ServerError::internal(format!("failed to preserve generated experiment: {error}"))
    })?;
    if let Err(error) = std::fs::rename(&merged, target) {
        let mut recovery_errors = Vec::new();
        if let Err(restore_error) = restore_path_checked(&generated, target) {
            recovery_errors.push(format!(
                "failed to restore generated experiment: {restore_error}"
            ));
        }
        if let Err(cleanup_error) = remove_path_raw(&merged) {
            recovery_errors.push(format!("failed to remove merge tree: {cleanup_error}"));
        }
        let mut server_error =
            ServerError::internal(format!("failed to install staged experiment: {error}"));
        if !recovery_errors.is_empty() {
            server_error = server_error.outcome("unknown").details(json!({
                "recovery_errors": recovery_errors,
                "preserved_paths": existing_paths([generated.as_path(), merged.as_path()]),
            }));
        }
        return Err(server_error);
    }
    remove_path_raw(&generated).map_err(|error| {
        ServerError::internal(format!(
            "staged experiment was installed but generated-tree cleanup failed: {error}"
        ))
        .outcome("unknown")
        .details(json!({"preserved_paths": [generated.display().to_string()]}))
    })?;
    Ok(())
}

fn copy_tree(
    source: &std::path::Path,
    destination: &std::path::Path,
    overwrite: bool,
) -> Result<(), ServerError> {
    std::fs::create_dir_all(destination).map_err(|error| {
        ServerError::internal(format!("failed to create merged directory: {error}"))
    })?;
    for entry in std::fs::read_dir(source).map_err(|error| {
        ServerError::internal(format!("failed to read experiment directory: {error}"))
    })? {
        let entry = entry.map_err(|error| {
            ServerError::internal(format!("failed to read experiment entry: {error}"))
        })?;
        let file_type = entry.file_type().map_err(|error| {
            ServerError::internal(format!("failed to inspect experiment entry: {error}"))
        })?;
        let output = destination.join(entry.file_name());
        if file_type.is_dir() {
            copy_tree(&entry.path(), &output, overwrite)?;
        } else if file_type.is_file() {
            if output.exists() && !overwrite {
                continue;
            }
            std::fs::copy(entry.path(), output).map_err(|error| {
                ServerError::internal(format!("failed to merge experiment file: {error}"))
            })?;
        } else {
            return Err(ServerError::bad_request(
                "experiment tree contains a link or special file",
            ));
        }
    }
    Ok(())
}

fn restore_path_checked(
    backup: &std::path::Path,
    destination: &std::path::Path,
) -> Result<(), String> {
    if !path_present(backup).map_err(|error| {
        format!(
            "failed to inspect backup {} before restoration: {error}",
            backup.display()
        )
    })? {
        return Ok(());
    }
    remove_path_raw(destination).map_err(|error| {
        format!(
            "failed to prepare restoration destination {}: {error}",
            destination.display()
        )
    })?;
    std::fs::rename(backup, destination).map_err(|error| {
        format!(
            "failed to rename backup {} to {}: {error}",
            backup.display(),
            destination.display()
        )
    })
}

fn path_present(path: &std::path::Path) -> std::io::Result<bool> {
    match std::fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error),
    }
}

fn remove_path_raw(path: &std::path::Path) -> std::io::Result<()> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    if metadata.file_type().is_dir() {
        std::fs::remove_dir_all(path)
    } else {
        std::fs::remove_file(path)
    }
}

fn remove_paths_checked<'a, P>(paths: impl IntoIterator<Item = (P, &'a str)>) -> Vec<String>
where
    P: AsRef<std::path::Path>,
{
    paths
        .into_iter()
        .filter_map(|(path, description)| {
            let path = path.as_ref();
            remove_path_raw(path)
                .err()
                .map(|error| format!("failed to remove {description} {}: {error}", path.display()))
        })
        .collect()
}

fn existing_paths<P>(paths: impl IntoIterator<Item = P>) -> Vec<String>
where
    P: AsRef<std::path::Path>,
{
    paths
        .into_iter()
        .filter_map(|path| {
            let path = path.as_ref();
            path_present(path)
                .unwrap_or(true)
                .then(|| path.display().to_string())
        })
        .collect()
}

fn filesystem_failure<P>(
    message: &str,
    recovery_errors: Vec<String>,
    possible_backups: impl IntoIterator<Item = P>,
    cause: Option<ExecutionFailure>,
) -> ExecutionFailure
where
    P: AsRef<std::path::Path>,
{
    let preserved_paths = existing_paths(possible_backups);
    let cause_details = cause.as_ref().map(|failure| {
        json!({
            "status": failure.error.status.as_u16(),
            "code": failure.error.code,
            "message": failure.error.message,
            "outcome": failure.error.outcome,
            "details": failure.error.details,
        })
    });
    let reconnect = cause.is_some_and(|failure| failure.reconnect);
    ExecutionFailure {
        error: ServerError::coded(
            StatusCode::INTERNAL_SERVER_ERROR,
            "filesystem_recovery_failed",
            format!("{message}: {}", recovery_errors.join("; ")),
        )
        .outcome("unknown")
        .details(json!({
            "recovery_errors": recovery_errors,
            "preserved_paths": preserved_paths,
            "cause": cause_details,
        })),
        reconnect,
    }
}

fn add_preserved_paths<P>(error: &mut ServerError, note: &str, paths: impl IntoIterator<Item = P>)
where
    P: AsRef<std::path::Path>,
{
    let previous = error.details.take();
    error.details = Some(json!({
        "note": note,
        "preserved_paths": existing_paths(paths),
        "cause_details": previous,
    }));
}

fn remove_path_checked(path: &std::path::Path) -> Result<(), ExecutionFailure> {
    remove_path_raw(path).map_err(|error| {
        ExecutionFailure::without_reconnect(
            ServerError::internal(format!("failed to delete experiment resource: {error}"))
                .outcome("unknown"),
        )
    })
}

fn subscription_stream(connection: &QSConnection) -> BroadcastStream<LogMessage> {
    if !connection.logchannels.contains_key("*") {
        let (sender, _) = tokio::sync::broadcast::channel(INSTRUMENT_EVENT_BUFFER);
        connection.logchannels.insert("*".to_string(), sender);
    }
    BroadcastStream::new(
        connection
            .logchannels
            .get("*")
            .expect("wildcard log channel was just installed")
            .subscribe(),
    )
}

async fn fetch_status(connection: &QSConnection) -> Result<InstrumentStatusDto, ExecutionFailure> {
    let machine = run_command(connection, MachineStatusQuery, QUERY_DEADLINE).await?;
    let power = run_command(connection, PowerQuery, QUERY_DEADLINE).await?;
    let block = run_command(connection, BlockQuery, QUERY_DEADLINE).await?;
    let zones = run_command(connection, ControlZonesQuery, QUERY_DEADLINE).await?;
    let indicator = run_command(connection, StatusLedQuery, QUERY_DEADLINE).await?;
    let run = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
    let remaining_time = fetch_remaining_time(connection).await?;
    Ok(InstrumentStatusDto::from_parts(
        machine,
        power,
        block,
        zones,
        indicator,
        run,
        remaining_time,
    ))
}

/// Remaining-time support is useful but not universal across instrument
/// software versions. A structured SCPI rejection therefore means "estimate
/// unavailable"; transport or malformed-response failures still evict the
/// managed connection as they do for every other status query.
async fn fetch_remaining_time(connection: &QSConnection) -> Result<Option<i64>, ExecutionFailure> {
    match run_command(connection, RemainingTimeQuery, QUERY_DEADLINE).await {
        Ok(remaining) => Ok(remaining.0),
        Err(failure) if !failure.reconnect => {
            debug!(
                error = %failure.error.message,
                "instrument does not provide a remaining-time estimate"
            );
            Ok(None)
        }
        Err(failure) => Err(failure),
    }
}

async fn set_and_verify_access(
    connection: &QSConnection,
    level: AccessLevel,
    exclusive: bool,
) -> Result<(), ExecutionFailure> {
    run_command(
        connection,
        AccessLevelSet::new(level.clone())
            .with_exclusive(exclusive)
            .with_stealth(false),
        CONTROL_DEADLINE,
    )
    .await?;
    let actual: AccessState = run_command(connection, AccessStateQuery, QUERY_DEADLINE).await?;
    if actual.level != level || actual.exclusive != exclusive || actual.stealth {
        return Err(ExecutionFailure::transport(format!(
            "access verification failed: requested ({level:?}, {exclusive}, false), got {actual:?}"
        )));
    }
    Ok(())
}

async fn verify_requested_run(
    connection: &QSConnection,
    requested: Option<&str>,
) -> Result<String, ExecutionFailure> {
    let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
    if status.state.eq_ignore_ascii_case("IDLE") || status.name == "-" {
        return Err(ExecutionFailure::without_reconnect(
            ServerError::coded(
                StatusCode::CONFLICT,
                "not_running",
                "there is no current run",
            )
            .details(json!({"current": RunStatusDto::from(status)})),
        ));
    }
    if let Some(requested) = requested {
        if status.name != requested {
            let current_name = status.name.clone();
            return Err(ExecutionFailure::without_reconnect(
                ServerError::coded(
                    StatusCode::CONFLICT,
                    "not_running",
                    format!("current run is {:?}, not {:?}", current_name, requested),
                )
                .details(json!({
                    "requested": requested,
                    "current": RunStatusDto::from(status),
                })),
            ));
        }
    }
    Ok(status.name)
}

async fn verify_run_state(
    connection: &QSConnection,
    requested: Option<&str>,
    predicate: impl Fn(&str) -> bool,
) -> Result<(), ExecutionFailure> {
    let deadline = Instant::now() + CONTROL_DEADLINE;
    loop {
        let status = run_command(connection, RunStatusQuery, QUERY_DEADLINE).await?;
        if requested
            .is_some_and(|name| status.name != name && !status.state.eq_ignore_ascii_case("IDLE"))
        {
            return Err(ExecutionFailure::without_reconnect(ServerError::conflict(
                "current run changed while verifying operation",
            )));
        }
        if predicate(&status.state.to_ascii_uppercase()) {
            return Ok(());
        }
        if Instant::now() >= deadline {
            return Err(ExecutionFailure::without_reconnect(
                ServerError::timeout("run did not reach the acknowledged state").outcome("unknown"),
            ));
        }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
}

async fn run_command<C>(
    connection: &QSConnection,
    command: C,
    deadline: Duration,
) -> Result<C::Response, ExecutionFailure>
where
    C: CommandBuilder<Error = ErrorResponse>,
    C::Response: TryFrom<OkResponse, Error = OkParseError>,
{
    let mut receiver = command.send(connection).await.map_err(|error| {
        ExecutionFailure::transport(format!("failed to submit SCPI command: {error}"))
    })?;
    let response = tokio::time::timeout(deadline, receiver.receive_response())
        .await
        .map_err(|_| ExecutionFailure::transport("SCPI command deadline exceeded"))?;
    match response {
        Ok(Ok(value)) => Ok(value),
        Ok(Err(error)) => Err(ExecutionFailure::without_reconnect(
            ServerError::instrument_rejection(error.to_string()),
        )),
        Err(ReceiveOkResponseError::ConnectionClosed) => Err(ExecutionFailure::transport(
            "SCPI connection closed before response",
        )),
        Err(ReceiveOkResponseError::Timeout) => Err(ExecutionFailure::transport(
            "SCPI response deadline exceeded",
        )),
        Err(error) => Err(ExecutionFailure::transport(format!(
            "invalid SCPI response: {error}"
        ))),
    }
}

async fn run_ack_command<C>(
    connection: &QSConnection,
    command: C,
    deadline: Duration,
) -> Result<(), ExecutionFailure>
where
    C: CommandBuilder<Error = ErrorResponse, Response = ()>,
{
    let mut receiver = command.send(connection).await.map_err(|error| {
        ExecutionFailure::transport(format!("failed to submit SCPI command: {error}"))
    })?;
    match tokio::time::timeout(deadline, receiver.receive_next()).await {
        Err(_) | Ok(Err(ReceiveNextResponseError::Timeout)) => Err(ExecutionFailure::transport(
            "SCPI acknowledgement deadline exceeded",
        )),
        Ok(Err(ReceiveNextResponseError::ConnectionClosed)) => Err(ExecutionFailure::transport(
            "SCPI connection closed before acknowledgement",
        )),
        Ok(Ok(Err(error))) => Err(ExecutionFailure::without_reconnect(
            ServerError::instrument_rejection(error.to_string()),
        )),
        Ok(Ok(Ok(()))) | Ok(Err(ReceiveNextResponseError::UnexpectedOk(_))) => Ok(()),
        Ok(Err(error)) => Err(ExecutionFailure::transport(format!(
            "invalid SCPI acknowledgement: {error}"
        ))),
    }
}

/// RUNStart needs to know whether the command reached the connection's send
/// queue before a response-side failure. Once submitted, deleting/restoring
/// its experiment tree is unsafe because the instrument may already be using
/// the new run even though the acknowledgement was lost.
///
/// (Text above generated by LLM)
async fn run_ack_command_tracking_submission<C>(
    connection: &QSConnection,
    command: C,
    deadline: Duration,
    possibly_accepted: &mut bool,
) -> Result<(), ExecutionFailure>
where
    C: CommandBuilder<Error = ErrorResponse, Response = ()>,
{
    let mut receiver = command.send(connection).await.map_err(|error| {
        ExecutionFailure::transport(format!("failed to submit SCPI command: {error}"))
    })?;
    *possibly_accepted = true;
    match tokio::time::timeout(deadline, receiver.receive_next()).await {
        Err(_) | Ok(Err(ReceiveNextResponseError::Timeout)) => Err(ExecutionFailure::transport(
            "SCPI acknowledgement deadline exceeded",
        )),
        Ok(Err(ReceiveNextResponseError::ConnectionClosed)) => Err(ExecutionFailure::transport(
            "SCPI connection closed before acknowledgement",
        )),
        Ok(Ok(Err(error))) => {
            // (Text below generated by LLM)
            // An explicit rejection proves RUNStart was not accepted, so the
            // pre-start filesystem rollback remains safe.
            *possibly_accepted = false;
            Err(ExecutionFailure::without_reconnect(
                ServerError::instrument_rejection(error.to_string()),
            ))
        }
        Ok(Ok(Ok(()))) | Ok(Err(ReceiveNextResponseError::UnexpectedOk(_))) => Ok(()),
        Ok(Err(error)) => Err(ExecutionFailure::transport(format!(
            "invalid SCPI acknowledgement: {error}"
        ))),
    }
}

async fn shutdown_connection(
    connection: QSConnection,
    health: &mut ServiceHealth,
    health_sender: &watch::Sender<ServiceHealth>,
) {
    if set_and_verify_access(&connection, AccessLevel::Observer, false)
        .await
        .is_err()
    {
        debug!("could not verify Observer during shutdown");
    }
    health.ready = false;
    health.current_access = None;
    let _ = health_sender.send(health.clone());
    connection.close().await;
}

fn jitter(base: Duration, generation: u64) -> Duration {
    // Deterministic bounded jitter avoids a random-number dependency on the
    // old instrument target while preventing synchronized reconnect storms.
    let percent = 85 + ((generation.wrapping_mul(37).wrapping_add(11)) % 31);
    base.mul_f64(percent as f64 / 100.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn status_fixture() -> InstrumentStatusDto {
        InstrumentStatusDto {
            observed_at: Utc::now(),
            power_enabled: true,
            block: crate::dto::BlockDto {
                enabled: true,
                target_c: 60.0,
            },
            zone_count: 2,
            drawer: "Closed".to_string(),
            cover: "Down".to_string(),
            lamp_status: "Off".to_string(),
            sample_temperatures_c: vec![25.0, 25.0],
            block_temperatures_c: vec![25.0, 25.0],
            cover_temperature_c: 30.0,
            target_temperatures_c: [("zone1".to_string(), 61.0), ("Zone2".to_string(), 62.0)]
                .into_iter()
                .collect(),
            target_controlled: Default::default(),
            led_temperature_c: 31.0,
            indicator: crate::dto::IndicatorDto {
                color: Some("green".to_string()),
                mode: "on".to_string(),
            },
            run: RunStatusDto {
                name: "seeded run".to_string(),
                stage: 2,
                stage_name: "Stage2".to_string(),
                num_stages: 4,
                cycle: 3,
                num_cycles: 10,
                step: 1,
                point: 2,
                state: "Running".to_string(),
                remaining_time_s: Some(42),
            },
        }
    }

    #[test]
    fn transport_failures_are_conservatively_outcome_unknown() {
        let failure = ExecutionFailure::transport("connection closed after submission");
        assert!(failure.reconnect);
        assert_eq!(failure.error.outcome, "unknown");
    }

    #[test]
    fn event_context_is_seeded_and_tracks_run_messages() {
        let status = status_fixture();
        let mut context = InstrumentEventContext::from_status(Some(&status));
        assert_eq!(context.run_name.as_deref(), Some("seeded run"));
        assert_eq!(context.zone_targets_c, vec![61.0, 62.0]);
        assert_eq!(
            (context.stage, context.cycle, context.step),
            (Some(2), Some(3), Some(1))
        );

        assert!(!context.observe("Run", "Starting \"new run\""));
        assert_eq!(context.run_name.as_deref(), Some("new run"));
        assert_eq!(
            (context.stage, context.cycle, context.step),
            (None, None, None)
        );

        assert!(!context.observe("Run", "Stage Stage2"));
        assert!(!context.observe("Run", "Cycle 7"));
        assert!(!context.observe("Run", "Step 3"));
        assert_eq!(
            (context.stage, context.cycle, context.step),
            (Some(2), Some(7), Some(3))
        );

        assert!(!context.observe("Run", "Stage POSTRun"));
        assert_eq!(context.stage, Some(2));
        assert_eq!((context.cycle, context.step), (None, None));
        assert!(!context.observe("Run", "Cycle 7"));
        assert!(!context.observe("Run", "Step 3"));

        assert!(!context.observe(
            "Run",
            "Ramping -zones=Cover,Zone2 -targets=105.0,72.5 -rates=0.1,1.6",
        ));
        assert_eq!(context.zone_targets_c, vec![61.0, 72.5]);

        assert!(!context.observe(
            "Run",
            "Collected -run=\"new run\" -stage=4 -cycle=8 -step=2 -point=1",
        ));
        assert_eq!(context.run_name.as_deref(), Some("new run"));
        assert_eq!(
            (context.stage, context.cycle, context.step),
            (Some(4), Some(8), Some(2))
        );
        assert!(context.observe("Run", "Ended"));
    }

    #[test]
    fn terminal_event_carries_final_context_then_clears_it() {
        let events = EventHub::new();
        let mut receiver = events.subscribe();
        let mut context = InstrumentEventContext::default();
        publish_instrument_event(
            &events,
            &mut context,
            LogMessage {
                topic: "Run".to_string(),
                timestamp: Some(1_700_000_000.0),
                message: "Starting \"replay run\"".to_string(),
            },
        );
        receiver.try_recv().unwrap();
        context.stage = Some(3);
        context.cycle = Some(4);
        context.step = Some(2);

        publish_instrument_event(
            &events,
            &mut context,
            LogMessage {
                topic: "Run".to_string(),
                timestamp: Some(1_700_000_001.0),
                message: "Ended".to_string(),
            },
        );
        let ended = receiver.try_recv().unwrap();
        assert_eq!(ended.data["context"]["run_name"], "replay run");
        assert_eq!(ended.data["context"]["stage"], 3);
        assert_eq!(ended.data["context"]["cycle"], 4);
        assert_eq!(ended.data["context"]["step"], 2);
        assert_eq!(context.run_name, None);
        assert_eq!(
            (context.stage, context.cycle, context.step),
            (None, None, None)
        );
    }

    #[test]
    fn checked_restore_preserves_the_backup_when_restoration_fails() {
        let root = tempfile::tempdir().unwrap();
        let backup = root.path().join("backup");
        std::fs::write(&backup, b"original").unwrap();
        let non_directory_parent = root.path().join("not-a-directory");
        std::fs::write(&non_directory_parent, b"blocker").unwrap();
        let destination = non_directory_parent.join("destination");

        let error = restore_path_checked(&backup, &destination).unwrap_err();

        assert!(error.contains("failed to prepare restoration destination"));
        assert_eq!(std::fs::read(&backup).unwrap(), b"original");
        assert!(!destination.exists());
    }

    #[test]
    fn incomplete_rollback_is_reported_as_unknown_with_preserved_paths() {
        let root = tempfile::tempdir().unwrap();
        let backup = root.path().join("preserved-backup");
        std::fs::write(&backup, b"original").unwrap();
        let cause = ExecutionFailure::without_reconnect(
            ServerError::conflict("instrument rejected the operation")
                .details(json!({"phase": "start"})),
        );

        let failure = filesystem_failure(
            "rollback was incomplete",
            vec!["rename failed".to_string()],
            [backup.as_path()],
            Some(cause),
        );

        assert_eq!(failure.error.code, "filesystem_recovery_failed");
        assert_eq!(failure.error.outcome, "unknown");
        let details = failure.error.details.unwrap();
        assert_eq!(details["recovery_errors"][0], "rename failed");
        assert_eq!(details["preserved_paths"][0], backup.display().to_string());
        assert_eq!(details["cause"]["code"], "conflict");
        assert_eq!(details["cause"]["details"]["phase"], "start");
    }
}
