//! Extension methods on the core [`QSConnection`] that return qslib domain
//! objects (plate setup, filter data, parsed protocol).
//!
//! These live in the `qslib` crate rather than `qslib-core` so the core stays
//! free of Polars/EDS types; the `qslib-server` binary does not pull them
//! in. Each method uses only the public core connection API (send a command,
//! read a response, fetch an experiment file) and then parses the result into a
//! qslib type.

use anyhow::Context;
use bstr::ByteSlice;

use crate::com::{CommandError, FilterDataFilename, QSConnection};
use crate::data::{FilterDataCollection, PlateData};
use crate::parser::{Command, ErrorResponse};
use crate::plate_setup::PlateSetup;
use crate::protocol::Protocol;
use crate::server_client::ServerClient;

/// Absolute on-instrument root of the experiments tree (the `experiments` SCPI
/// file context; see the Python `_SCPI_CONTEXT_ROOTS`). The server client maps
/// this legacy absolute spelling to the corresponding named HTTP context.
pub const INSTRUMENT_EXPERIMENTS_ROOT: &str = "/data/vendor/IS/experiments";

/// Domain-object convenience methods on a core SCPI [`QSConnection`].
///
/// Bring this trait into scope to call the methods on a connection value.
///
/// The `_via` variants take an optional [`ServerClient`]: when present, the
/// underlying experiment file is fetched from qslib-server's named file
/// resource (raw off disk, no base64+TLS overhead on the instrument), falling
/// back to SCPI on a read/transport error. An HTTP 401/403 is surfaced instead:
/// bypassing an explicit server policy decision through direct SCPI would be a
/// privilege boundary violation. The plain methods are the SCPI-only path
/// (`server = None`).
///
/// (Text above generated by LLM)
#[allow(async_fn_in_trait)]
pub trait QSConnectionExt {
    /// Fetch and parse the plate setup for a run (or the current run).
    async fn get_plate_setup(
        &self,
        run: Option<String>,
    ) -> Result<PlateSetup, CommandError<ErrorResponse>>;

    /// Like [`get_plate_setup`](Self::get_plate_setup), preferring qslib-server
    /// when `server` is provided.
    async fn get_plate_setup_via(
        &self,
        server: Option<&ServerClient>,
        run: Option<String>,
    ) -> Result<PlateSetup, CommandError<ErrorResponse>>;

    /// Fetch the currently running protocol and parse it into a [`Protocol`].
    async fn get_running_protocol(&self) -> Result<Protocol, CommandError<ErrorResponse>>;

    /// Fetch and parse a single filter-data file into a [`PlateData`].
    async fn get_filterdata_one(
        &self,
        fref: FilterDataFilename,
        run: Option<String>,
    ) -> Result<PlateData, CommandError<ErrorResponse>>;

    /// Like [`get_filterdata_one`](Self::get_filterdata_one), preferring
    /// qslib-server when `server` is provided.
    async fn get_filterdata_one_via(
        &self,
        server: Option<&ServerClient>,
        fref: FilterDataFilename,
        run: Option<String>,
    ) -> Result<PlateData, CommandError<ErrorResponse>>;
}

/// Fetch an experiment file under a run's `apldbio/sds/` directory, preferring
/// qslib-server's named file resource when `server` is set and falling back to
/// SCPI.
///
/// `sds_subpath` is relative to `apldbio/sds/` (e.g. `"plate_setup.xml"` or
/// `"filter/<name>"`). `scpi_var_path` is the SCPI-side path used when
/// qslib-server is absent or its fetch fails without an authorization response
/// (using the InstrumentServer's `${LogFolder}` / `${FilterFolder}` variables
/// for the current run).
///
/// (Text above generated by LLM)
async fn fetch_sds_file(
    con: &QSConnection,
    server: Option<&ServerClient>,
    run: &Option<String>,
    sds_subpath: &str,
    scpi_var_path: &str,
) -> Result<Vec<u8>, CommandError<ErrorResponse>> {
    if let Some(server) = server {
        // qslib-server serves by absolute path, so resolve the run title (the
        // experiment folder name) for the current run.
        let runtitle = match run {
            Some(r) => Some(r.clone()),
            None => con.get_run_title().await.ok(),
        };
        if let Some(rt) = runtitle {
            let abspath = format!("{INSTRUMENT_EXPERIMENTS_ROOT}/{rt}/apldbio/sds/{sds_subpath}");
            match server.get_abs_file(&abspath).await {
                Ok(bytes) => return Ok(bytes),
                Err(error) if error.is_authorization_failure() => {
                    return Err(CommandError::InternalError(anyhow::Error::new(error)));
                }
                Err(e) => {
                    log::debug!(
                        "qslib-server fetch of {abspath} failed ({e}); falling back to SCPI"
                    );
                }
            }
        }
    }
    let path = match run {
        Some(r) => format!("{r}/apldbio/sds/{sds_subpath}"),
        None => scpi_var_path.to_string(),
    };
    con.get_exp_file(&path).await
}

impl QSConnectionExt for QSConnection {
    async fn get_plate_setup(
        &self,
        run: Option<String>,
    ) -> Result<PlateSetup, CommandError<ErrorResponse>> {
        self.get_plate_setup_via(None, run).await
    }

    async fn get_plate_setup_via(
        &self,
        server: Option<&ServerClient>,
        run: Option<String>,
    ) -> Result<PlateSetup, CommandError<ErrorResponse>> {
        let x = fetch_sds_file(
            self,
            server,
            &run,
            "plate_setup.xml",
            "${LogFolder}/plate_setup.xml",
        )
        .await?;
        let plate_setup: PlateSetup = quick_xml::de::from_str(&x.to_str_lossy())
            .with_context(|| "PlateSetup deserialization error")
            .map_err(CommandError::InternalError)?;

        Ok(plate_setup)
    }

    async fn get_running_protocol(&self) -> Result<Protocol, CommandError<ErrorResponse>> {
        let prot_command = self.get_running_protocol_string().await?;

        // Parse into Command and then Protocol
        let cmd = Command::try_from(prot_command.clone()).map_err(|e| {
            CommandError::InternalError(anyhow::anyhow!("Failed to parse protocol command: {}", e))
        })?;

        Protocol::from_scpicommand(&cmd).map_err(|e| {
            CommandError::InternalError(anyhow::anyhow!("Failed to parse protocol: {}", e))
        })
    }

    async fn get_filterdata_one(
        &self,
        fref: FilterDataFilename,
        run: Option<String>,
    ) -> Result<PlateData, CommandError<ErrorResponse>> {
        self.get_filterdata_one_via(None, fref, run).await
    }

    async fn get_filterdata_one_via(
        &self,
        server: Option<&ServerClient>,
        fref: FilterDataFilename,
        run: Option<String>,
    ) -> Result<PlateData, CommandError<ErrorResponse>> {
        let x = fetch_sds_file(
            self,
            server,
            &run,
            &format!("filter/{fref}"),
            &format!("${{FilterFolder}}/{fref}"),
        )
        .await?;

        let filter_data_collection: FilterDataCollection =
            quick_xml::de::from_str(&x.to_str_lossy())
                .with_context(|| "PlatePointData deserialization error")
                .map_err(CommandError::InternalError)?;

        let plate_point_data = filter_data_collection
            .plate_point_data
            .into_iter()
            .next()
            .ok_or_else(|| {
                CommandError::InternalError(anyhow::anyhow!("No PlatePointData found"))
            })?;
        let plate_data = plate_point_data
            .plate_data
            .into_iter()
            .next()
            .ok_or_else(|| CommandError::InternalError(anyhow::anyhow!("No PlateData found")))?;
        Ok(plate_data)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio::net::TcpListener;
    use tokio::time::{timeout, Duration};

    async fn idle_scpi_connection() -> (QSConnection, tokio::task::JoinHandle<Vec<u8>>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let task = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            socket
                .write_all(
                    b"READy -session=1 -product=Test -version=1 -build=1 -capabilities=Index\n",
                )
                .await
                .unwrap();
            let mut buffer = vec![0_u8; 2048];
            match timeout(Duration::from_millis(250), socket.read(&mut buffer)).await {
                Ok(Ok(count)) => {
                    buffer.truncate(count);
                    buffer
                }
                Ok(Err(error)) => panic!("reading mock SCPI connection: {error}"),
                Err(_) => Vec::new(),
            }
        });
        let connection = QSConnection::connect_tcp("127.0.0.1", address.port())
            .await
            .unwrap();
        (connection, task)
    }

    async fn rejecting_file_server(
        status: u16,
    ) -> (ServerClient, tokio::task::JoinHandle<Vec<u8>>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let task = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request = Vec::new();
            let mut buffer = [0_u8; 1024];
            while !request.windows(4).any(|part| part == b"\r\n\r\n") {
                let read = socket.read(&mut buffer).await.unwrap();
                assert!(read > 0, "client closed before completing HTTP request");
                request.extend_from_slice(&buffer[..read]);
            }
            let reason = if status == 401 {
                "Unauthorized"
            } else {
                "Forbidden"
            };
            let body = br#"{"error":{"code":"unauthorized","message":"credentials rejected","retryable":false,"outcome":"not_started"}}"#;
            socket
                .write_all(
                    format!(
                        "HTTP/1.1 {status} {reason}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
                        body.len()
                    )
                    .as_bytes(),
                )
                .await
                .unwrap();
            socket.write_all(body).await.unwrap();
            request
        });
        (
            ServerClient::new(
                "127.0.0.1",
                address.port(),
                Some("revoked-token".to_string()),
            ),
            task,
        )
    }

    #[tokio::test]
    async fn file_authorization_failure_never_falls_back_to_direct_scpi() {
        for status in [401, 403] {
            let (connection, scpi_request) = idle_scpi_connection().await;
            let (server, http_request) = rejecting_file_server(status).await;

            let error = fetch_sds_file(
                &connection,
                Some(&server),
                &Some("active-run".to_string()),
                "plate_setup.xml",
                "${LogFolder}/plate_setup.xml",
            )
            .await
            .unwrap_err();

            let message = error.to_string();
            assert!(message.contains(&format!("HTTP {status}")), "{message}");
            let request = http_request.await.unwrap();
            assert!(request.starts_with(
                b"GET /api/v1/files/experiments/active-run/apldbio/sds/plate_setup.xml"
            ));
            assert_eq!(scpi_request.await.unwrap(), b"");
        }
    }
}
