//! Typed client for qslib-server's optional `/api/v1` HTTP API.

use std::collections::HashMap;
use std::pin::Pin;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use futures::StreamExt;
use serde::{Deserialize, Serialize};
use tokio::sync::OnceCell;

pub const DEFAULT_SERVER_PORT: u16 = 7500;
const CONNECT_TIMEOUT: Duration = Duration::from_secs(3);
const REQUEST_TIMEOUT: Duration = Duration::from_secs(120);
const NEGATIVE_CACHE: Duration = Duration::from_secs(30);
type EventByteStream =
    Pin<Box<dyn futures::Stream<Item = Result<bytes::Bytes, reqwest::Error>> + Send>>;

#[derive(Debug, thiserror::Error)]
pub enum ServerError {
    #[error("cannot reach qslib-server at {url}: {source}")]
    Unreachable {
        url: String,
        submitted: bool,
        #[source]
        source: reqwest::Error,
    },
    #[error("qslib-server returned HTTP {status}: {message}")]
    Http {
        status: u16,
        code: Option<String>,
        message: String,
        retryable: bool,
        outcome: Option<String>,
        request_id: Option<String>,
    },
    #[error("qslib-server response error: {0}")]
    Decode(String),
    #[error("{abspath} does not map to a named qslib-server file context")]
    NotUnderRoot { abspath: String },
    #[error("server mutation outcome is unknown; query {state_query}")]
    OutcomeUnknown { state_query: String },
}

impl ServerError {
    /// Whether the server reached a policy decision for this identity.
    ///
    /// Authorization failures are not optional-service outages: callers must
    /// surface them instead of negative-caching the probe or falling back to a
    /// less restricted transport.
    ///
    /// (Text above generated by LLM)
    pub fn is_authorization_failure(&self) -> bool {
        matches!(
            self,
            Self::Http {
                status: 401 | 403,
                ..
            }
        )
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct Health {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub executable_sha256: String,
    #[serde(default)]
    pub uptime_s: u64,
    #[serde(default)]
    pub ready: bool,
    #[serde(default)]
    pub generation: u64,
    #[serde(default)]
    pub reconnect_count: u64,
    #[serde(default)]
    pub queue_depth: usize,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Capabilities {
    pub api_version: String,
    #[serde(default)]
    pub resources: Vec<String>,
    #[serde(default)]
    pub file_contexts: Vec<String>,
    pub max_access: String,
    pub sse: bool,
    #[serde(default)]
    pub sse_cursor_format: Option<String>,
    #[serde(default)]
    pub sse_event_context: bool,
    #[serde(default)]
    pub sse_initial_snapshot: bool,
    pub raw_scpi: bool,
    pub scpi_tunnel: bool,
    pub file_writes: bool,
    pub controls: bool,
}

impl Capabilities {
    pub fn supports(&self, resource: &str) -> bool {
        self.resources.iter().any(|candidate| candidate == resource)
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct IndicatorStatus {
    pub color: Option<String>,
    pub mode: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct BlockStatus {
    pub enabled: bool,
    pub target_c: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RunStatusDto {
    pub name: String,
    pub stage: i64,
    pub stage_name: String,
    pub num_stages: i64,
    pub cycle: i64,
    pub num_cycles: i64,
    pub step: i64,
    pub point: i64,
    pub state: String,
    #[serde(default)]
    pub remaining_time_s: Option<i64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InstrumentStatus {
    pub observed_at: String,
    pub power_enabled: bool,
    pub block: BlockStatus,
    pub zone_count: usize,
    pub drawer: String,
    pub cover: String,
    pub lamp_status: String,
    pub sample_temperatures_c: Vec<f64>,
    pub block_temperatures_c: Vec<f64>,
    pub cover_temperature_c: f64,
    pub target_temperatures_c: HashMap<String, f64>,
    pub target_controlled: HashMap<String, bool>,
    pub led_temperature_c: f64,
    pub indicator: IndicatorStatus,
    pub run: RunStatusDto,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OperationRecord {
    pub id: String,
    pub kind: String,
    pub state: String,
    #[serde(default)]
    pub result: Option<serde_json::Value>,
    #[serde(default)]
    pub error: Option<serde_json::Value>,
    pub outcome: String,
}

#[derive(Debug, Clone)]
pub struct ServerEvent {
    /// Opaque SSE cursor; do not parse or perform arithmetic on it.
    pub id: Option<String>,
    pub event: String,
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ListEntry {
    pub path: String,
    #[serde(rename = "type")]
    pub kind: String,
    pub size: u64,
    pub mtime: f64,
    pub atime: f64,
    pub ctime: f64,
    pub attributes: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ExperimentsResource {
    #[serde(default)]
    pub experiments: Vec<String>,
    #[serde(default)]
    pub staged: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ExperimentResource {
    pub name: String,
    pub working: bool,
    pub package_etag: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct StagedPackage {
    pub name: String,
    pub etag: String,
    pub compressed_size: usize,
    pub expanded_size: u64,
    pub entries: usize,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RunsResource {
    pub location: String,
    #[serde(default)]
    pub runs: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RunResource {
    pub name: String,
    pub working: bool,
    pub completed: bool,
}

/// Exact protocol currently being executed by the instrument.
///
/// `scpi` is the authoritative definition.  The other fields are server-parsed
/// metadata provided so callers do not need to partially parse that command.
///
/// (Text above generated by LLM)
#[derive(Debug, Clone, Deserialize, PartialEq)]
pub struct RunningProtocol {
    pub name: String,
    pub sample_volume: f64,
    pub run_mode: String,
    pub scpi: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct StartRunRequest {
    pub experiment: String,
    pub package_etag: String,
    pub overwrite: String,
    pub require_exclusive: bool,
    pub require_drawer_check: bool,
}

#[derive(Deserialize)]
struct ListResponse {
    entries: Vec<ListEntry>,
}

#[derive(Debug, Clone)]
pub struct ServerClient {
    base_url: String,
    token: Option<String>,
    client: reqwest::Client,
    capabilities: Arc<OnceCell<Capabilities>>,
    retry_at: Arc<Mutex<Option<Instant>>>,
}

impl ServerClient {
    pub fn new(host: &str, port: u16, token: Option<String>) -> Self {
        let client = reqwest::Client::builder()
            .connect_timeout(CONNECT_TIMEOUT)
            .timeout(REQUEST_TIMEOUT)
            .build()
            .expect("building qslib-server HTTP client");
        Self {
            base_url: format!("http://{host}:{port}"),
            token,
            client,
            capabilities: Arc::new(OnceCell::new()),
            retry_at: Arc::new(Mutex::new(None)),
        }
    }

    pub fn base_url(&self) -> &str {
        &self.base_url
    }

    pub async fn health(&self) -> Result<Health, ServerError> {
        self.get_json("/health").await
    }

    pub async fn available(&self) -> bool {
        matches!(self.health().await, Ok(health) if health.ready)
    }

    /// Query capabilities once, with a 30-second negative cache. Constructing
    /// a client does not probe the server.
    pub async fn capabilities(&self) -> Result<Capabilities, ServerError> {
        if let Some(capabilities) = self.capabilities.get() {
            return Ok(capabilities.clone());
        }
        if self.probe_suppressed() {
            return Err(ServerError::Decode(
                "qslib-server capability probe is negatively cached".to_string(),
            ));
        }
        match self.get_json::<Capabilities>("/api/v1/capabilities").await {
            Ok(capabilities) if capabilities.api_version == "v1" => {
                *self
                    .retry_at
                    .lock()
                    .unwrap_or_else(|value| value.into_inner()) = None;
                let _ = self.capabilities.set(capabilities.clone());
                Ok(capabilities)
            }
            Ok(capabilities) => {
                *self
                    .retry_at
                    .lock()
                    .unwrap_or_else(|value| value.into_inner()) =
                    Some(Instant::now() + NEGATIVE_CACHE);
                Err(ServerError::Decode(format!(
                    "qslib-server API {} is not compatible with v1",
                    capabilities.api_version
                )))
            }
            Err(error) => {
                let retry_at = if error.is_authorization_failure() {
                    None
                } else {
                    Some(Instant::now() + NEGATIVE_CACHE)
                };
                *self
                    .retry_at
                    .lock()
                    .unwrap_or_else(|value| value.into_inner()) = retry_at;
                Err(error)
            }
        }
    }

    pub async fn instrument_status(&self) -> Result<InstrumentStatus, ServerError> {
        self.get_json("/api/v1/instrument/status").await
    }

    pub async fn current_run(&self) -> Result<RunStatusDto, ServerError> {
        self.get_json("/api/v1/runs/current").await
    }

    pub async fn set_power(&self, enabled: bool) -> Result<(), ServerError> {
        self.put_json(
            "/api/v1/instrument/power",
            &serde_json::json!({"enabled": enabled}),
            "/api/v1/instrument/status",
        )
        .await
    }

    pub async fn set_block(&self, enabled: bool, target_c: Option<f64>) -> Result<(), ServerError> {
        self.put_json(
            "/api/v1/instrument/block",
            &serde_json::json!({"enabled": enabled, "target_c": target_c}),
            "/api/v1/instrument/status",
        )
        .await
    }

    pub async fn set_indicator(&self, color: &str, mode: &str) -> Result<(), ServerError> {
        self.put_json(
            "/api/v1/instrument/indicator",
            &serde_json::json!({"color": color, "mode": mode}),
            "/api/v1/instrument/status",
        )
        .await
    }

    pub async fn set_drawer(
        &self,
        position: &str,
        lower_cover: bool,
        verify: bool,
    ) -> Result<(), ServerError> {
        self.put_json(
            "/api/v1/instrument/drawer",
            &serde_json::json!({
                "position": position,
                "lower_cover": lower_cover,
                "verify": verify,
            }),
            "/api/v1/instrument/status",
        )
        .await
    }

    pub async fn set_cover(&self, position: &str, verify: bool) -> Result<(), ServerError> {
        self.put_json(
            "/api/v1/instrument/cover",
            &serde_json::json!({"position": position, "verify": verify}),
            "/api/v1/instrument/status",
        )
        .await
    }

    pub async fn list_experiments(&self) -> Result<ExperimentsResource, ServerError> {
        self.get_json("/api/v1/experiments").await
    }

    pub async fn experiment(&self, name: &str) -> Result<ExperimentResource, ServerError> {
        self.get_json(&format!("/api/v1/experiments/{}", encode_segment(name)))
            .await
    }

    pub async fn stage_package(
        &self,
        name: &str,
        package: Vec<u8>,
    ) -> Result<StagedPackage, ServerError> {
        let path = format!("/api/v1/experiments/{}/package", encode_segment(name));
        let request = self
            .authorize(self.client.put(self.url(&path)?))
            .header(reqwest::header::CONTENT_TYPE, "application/zip")
            .body(package);
        self.send_json(request, true, &path).await
    }

    pub async fn package(&self, name: &str) -> Result<Vec<u8>, ServerError> {
        let path = format!("/api/v1/experiments/{}/package", encode_segment(name));
        let response = self
            .send(self.authorize(self.client.get(self.url(&path)?)), false)
            .await?;
        response
            .bytes()
            .await
            .map(|bytes| bytes.to_vec())
            .map_err(|error| ServerError::Decode(format!("reading experiment package: {error}")))
    }

    pub async fn delete_experiment(&self, name: &str) -> Result<(), ServerError> {
        let path = format!("/api/v1/experiments/{}", encode_segment(name));
        let request = self.authorize(self.client.delete(self.url(&path)?));
        self.send_mutation(request, &path).await?;
        Ok(())
    }

    pub async fn list_runs(&self, location: &str) -> Result<RunsResource, ServerError> {
        let mut url = self.url("/api/v1/runs")?;
        url.query_pairs_mut().append_pair("location", location);
        let request = self.authorize(self.client.get(url));
        self.send_json(request, false, "/api/v1/runs").await
    }

    pub async fn run(&self, name: &str) -> Result<RunResource, ServerError> {
        self.get_json(&format!("/api/v1/runs/{}", encode_segment(name)))
            .await
    }

    pub async fn start_run(
        &self,
        input: &StartRunRequest,
        idempotency_key: &str,
    ) -> Result<OperationRecord, ServerError> {
        let request = self
            .authorize(self.client.post(self.url("/api/v1/runs")?))
            .header("Idempotency-Key", idempotency_key)
            .json(input);
        self.send_json(request, true, "/api/v1/runs/current").await
    }

    /// Return the instrument's authoritative active protocol.
    ///
    /// (Text above generated by LLM)
    pub async fn running_protocol(&self) -> Result<RunningProtocol, ServerError> {
        self.get_json("/api/v1/runs/current/protocol").await
    }

    pub async fn replace_protocol(
        &self,
        name: &str,
        scpi: &str,
        tcprotocol_xml: &str,
        mode: &str,
    ) -> Result<(), ServerError> {
        let path = format!("/api/v1/runs/{}/protocol", encode_segment(name));
        let mut url = self.url(&path)?;
        url.query_pairs_mut().append_pair("mode", mode);
        let request = self
            .authorize(self.client.put(url))
            .json(&serde_json::json!({
                "scpi": scpi,
                "tcprotocol_xml": tcprotocol_xml,
            }));
        self.send_mutation(request, "/api/v1/runs/current/protocol")
            .await?;
        Ok(())
    }

    pub async fn eds(&self, name: &str) -> Result<Vec<u8>, ServerError> {
        let path = format!("/api/v1/runs/{}/eds", encode_segment(name));
        let response = self
            .send(self.authorize(self.client.get(self.url(&path)?)), false)
            .await?;
        response
            .bytes()
            .await
            .map(|bytes| bytes.to_vec())
            .map_err(|error| ServerError::Decode(format!("reading EDS: {error}")))
    }

    pub async fn generate_access_key(
        &self,
        idempotency_key: &str,
    ) -> Result<OperationRecord, ServerError> {
        let request = self
            .authorize(
                self.client
                    .post(self.url("/api/v1/instrument/access-keys")?),
            )
            .header("Idempotency-Key", idempotency_key);
        self.send_json(request, true, "/api/v1/instrument/status")
            .await
    }

    pub async fn restart_instrument(
        &self,
        idempotency_key: &str,
    ) -> Result<OperationRecord, ServerError> {
        let request = self
            .authorize(
                self.client
                    .post(self.url("/api/v1/instrument/actions/restart")?),
            )
            .header("Idempotency-Key", idempotency_key);
        self.send_json(request, true, "/health").await
    }

    /// Administrator-only isolated raw SCPI. This never uses the managed
    /// managed SCPI connection and exists only when the server advertises it.
    pub async fn raw_scpi(&self, command: &str) -> Result<String, ServerError> {
        let request = self
            .authorize(self.client.post(self.url("/api/v1/scpi")?))
            .json(&serde_json::json!({"command": command, "encoding": "text"}));
        let response = self
            .send_mutation(request, "/api/v1/instrument/status")
            .await?;
        response
            .text()
            .await
            .map_err(|_error| ServerError::OutcomeUnknown {
                state_query: "/api/v1/instrument/status".to_string(),
            })
    }

    pub async fn run_action(
        &self,
        name: &str,
        action: &str,
        idempotency_key: &str,
    ) -> Result<OperationRecord, ServerError> {
        let path = format!(
            "/api/v1/runs/{}/actions/{}",
            encode_segment(name),
            encode_segment(action)
        );
        let request = self
            .authorize(self.client.post(self.url(&path)?))
            .header("Idempotency-Key", idempotency_key);
        self.send_json(
            request,
            true,
            &format!("/api/v1/runs/{}", encode_segment(name)),
        )
        .await
    }

    pub async fn operation(&self, id: &str) -> Result<OperationRecord, ServerError> {
        self.get_json(&format!("/api/v1/operations/{}", encode_segment(id)))
            .await
    }

    pub async fn wait_operation(
        &self,
        id: &str,
        timeout: Duration,
    ) -> Result<OperationRecord, ServerError> {
        let deadline = Instant::now() + timeout;
        loop {
            let operation = self.operation(id).await?;
            if matches!(operation.state.as_str(), "succeeded" | "failed" | "unknown") {
                return Ok(operation);
            }
            if Instant::now() >= deadline {
                return Err(ServerError::OutcomeUnknown {
                    state_query: format!("/api/v1/operations/{id}"),
                });
            }
            tokio::time::sleep(Duration::from_millis(250)).await;
        }
    }

    pub async fn get_file(&self, context: &str, path: &str) -> Result<Vec<u8>, ServerError> {
        let url = self.resource_url("files", context, path)?;
        let response = self
            .send(self.authorize(self.client.get(url)), false)
            .await?;
        response
            .bytes()
            .await
            .map(|bytes| bytes.to_vec())
            .map_err(|error| ServerError::Decode(format!("reading file response: {error}")))
    }

    pub async fn put_file(
        &self,
        context: &str,
        path: &str,
        body: Vec<u8>,
    ) -> Result<(), ServerError> {
        let url = self.resource_url("files", context, path)?;
        let request = self
            .authorize(self.client.put(url))
            .header(reqwest::header::CONTENT_TYPE, "application/octet-stream")
            .body(body);
        self.send_mutation(
            request,
            &format!("/api/v1/files/{context}/{}", encode_path(path)),
        )
        .await?;
        Ok(())
    }

    pub async fn list_context_dir(
        &self,
        context: &str,
        path: &str,
    ) -> Result<Vec<ListEntry>, ServerError> {
        let url = if path.is_empty() {
            self.url(&format!("/api/v1/directories/{}", encode_segment(context)))?
        } else {
            self.resource_url("directories", context, path)?
        };
        let response = self
            .send(self.authorize(self.client.get(url)), false)
            .await?;
        let bytes = response
            .bytes()
            .await
            .map_err(|error| ServerError::Decode(format!("reading directory response: {error}")))?;
        serde_json::from_slice::<ListResponse>(&bytes)
            .map(|response| response.entries)
            .map_err(|error| ServerError::Decode(format!("decoding directory response: {error}")))
    }

    /// Compatibility helper for QSLib's direct file API. Resolution is local
    /// and never depends on a tunnel or a successful health probe.
    pub async fn get_abs_file(&self, absolute: &str) -> Result<Vec<u8>, ServerError> {
        let (context, relative) =
            absolute_context(absolute).ok_or_else(|| ServerError::NotUnderRoot {
                abspath: absolute.into(),
            })?;
        self.get_file(context, &relative).await
    }

    pub async fn put_abs_file(&self, absolute: &str, body: Vec<u8>) -> Result<(), ServerError> {
        let (context, relative) =
            absolute_context(absolute).ok_or_else(|| ServerError::NotUnderRoot {
                abspath: absolute.into(),
            })?;
        self.put_file(context, &relative, body).await
    }

    pub async fn list_dir(&self, absolute: &str) -> Result<Vec<ListEntry>, ServerError> {
        let (context, relative) =
            absolute_context(absolute).ok_or_else(|| ServerError::NotUnderRoot {
                abspath: absolute.into(),
            })?;
        self.list_context_dir(context, &relative).await
    }

    /// Compatibility entry point for pre-epoch qslib-server cursors.
    pub async fn event_stream(&self, last_event_id: Option<u64>) -> ServerEventStream {
        self.event_stream_from_cursor(last_event_id.map(|id| id.to_string()))
            .await
    }

    /// Open a resumable event stream using an opaque SSE cursor.
    pub async fn event_stream_from_cursor(
        &self,
        last_event_id: Option<String>,
    ) -> ServerEventStream {
        ServerEventStream {
            client: self.clone(),
            last_event_id,
            stream: None,
            bytes: Vec::new(),
        }
    }

    async fn get_json<T: for<'de> Deserialize<'de>>(&self, path: &str) -> Result<T, ServerError> {
        let request = self.authorize(self.client.get(self.url(path)?));
        self.send_json(request, false, path).await
    }

    async fn put_json<T: Serialize + ?Sized>(
        &self,
        path: &str,
        value: &T,
        state_query: &str,
    ) -> Result<(), ServerError> {
        let request = self.authorize(self.client.put(self.url(path)?)).json(value);
        self.send_mutation(request, state_query).await?;
        Ok(())
    }

    async fn send_json<T: for<'de> Deserialize<'de>>(
        &self,
        request: reqwest::RequestBuilder,
        mutation: bool,
        state_query: &str,
    ) -> Result<T, ServerError> {
        let response = if mutation {
            self.send_mutation(request, state_query).await?
        } else {
            self.send(request, false).await?
        };
        let bytes = response.bytes().await.map_err(|error| {
            if mutation {
                ServerError::OutcomeUnknown {
                    state_query: state_query.to_string(),
                }
            } else {
                ServerError::Decode(format!("reading JSON response: {error}"))
            }
        })?;
        serde_json::from_slice(&bytes).map_err(|error| {
            if mutation {
                ServerError::OutcomeUnknown {
                    state_query: state_query.to_string(),
                }
            } else {
                ServerError::Decode(format!("decoding JSON response: {error}"))
            }
        })
    }

    async fn send_mutation(
        &self,
        request: reqwest::RequestBuilder,
        state_query: &str,
    ) -> Result<reqwest::Response, ServerError> {
        match self.send(request, true).await {
            Err(ServerError::Unreachable {
                submitted: true, ..
            }) => Err(ServerError::OutcomeUnknown {
                state_query: state_query.to_string(),
            }),
            Err(ServerError::Http {
                outcome: Some(outcome),
                ..
            }) if outcome == "unknown" => Err(ServerError::OutcomeUnknown {
                state_query: state_query.to_string(),
            }),
            result => result,
        }
    }

    async fn send(
        &self,
        request: reqwest::RequestBuilder,
        mutation: bool,
    ) -> Result<reqwest::Response, ServerError> {
        let response = request
            .send()
            .await
            .map_err(|source| ServerError::Unreachable {
                url: self.base_url.clone(),
                submitted: mutation && !source.is_connect(),
                source,
            })?;
        let status = response.status();
        if status.is_success() {
            return Ok(response);
        }
        let request_id = response
            .headers()
            .get("x-request-id")
            .and_then(|value| value.to_str().ok())
            .map(str::to_string);
        let body = response.bytes().await.unwrap_or_default();
        let parsed = serde_json::from_slice::<serde_json::Value>(&body).unwrap_or_default();
        let detail = parsed.get("error").cloned().unwrap_or_default();
        Err(ServerError::Http {
            status: status.as_u16(),
            code: detail.get("code").and_then(ValueExt::string),
            message: detail
                .get("message")
                .and_then(|value| value.as_str())
                .unwrap_or_else(|| status.canonical_reason().unwrap_or("server error"))
                .to_string(),
            retryable: detail
                .get("retryable")
                .and_then(|value| value.as_bool())
                .unwrap_or(false),
            outcome: detail.get("outcome").and_then(ValueExt::string),
            request_id: parsed
                .get("request_id")
                .and_then(ValueExt::string)
                .or(request_id),
        })
    }

    fn authorize(&self, request: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        match &self.token {
            Some(token) => request.bearer_auth(token),
            None => request,
        }
    }

    fn url(&self, path: &str) -> Result<reqwest::Url, ServerError> {
        reqwest::Url::parse(&format!("{}{}", self.base_url, path))
            .map_err(|error| ServerError::Decode(format!("invalid server URL: {error}")))
    }

    fn resource_url(
        &self,
        resource: &str,
        context: &str,
        path: &str,
    ) -> Result<reqwest::Url, ServerError> {
        self.url(&format!(
            "/api/v1/{}/{}/{}",
            resource,
            encode_segment(context),
            encode_path(path)
        ))
    }

    fn probe_suppressed(&self) -> bool {
        self.retry_at
            .lock()
            .unwrap_or_else(|value| value.into_inner())
            .is_some_and(|retry_at| Instant::now() < retry_at)
    }
}

pub struct ServerEventStream {
    client: ServerClient,
    last_event_id: Option<String>,
    stream: Option<EventByteStream>,
    bytes: Vec<u8>,
}

impl ServerEventStream {
    pub async fn next(&mut self) -> Result<ServerEvent, ServerError> {
        loop {
            if let Some(event) = take_sse_event(&mut self.bytes)? {
                self.last_event_id = event.id.clone().or_else(|| self.last_event_id.clone());
                return Ok(event);
            }
            if self.stream.is_none() {
                let mut request = self
                    .client
                    .authorize(self.client.client.get(self.client.url("/api/v1/events")?));
                if let Some(id) = self.last_event_id.as_ref() {
                    request = request.header("Last-Event-ID", id);
                }
                let response = self.client.send(request, false).await?;
                self.stream = Some(Box::pin(response.bytes_stream()));
            }
            let stream = self.stream.as_mut().expect("stream initialized");
            match stream.next().await {
                Some(Ok(chunk)) => {
                    self.bytes.extend_from_slice(&chunk);
                }
                Some(Err(_)) | None => {
                    self.stream = None;
                    // A partial SSE block has no acknowledged cursor and must
                    // be discarded before replay, never joined to new bytes.
                    self.bytes.clear();
                    tokio::time::sleep(Duration::from_millis(250)).await;
                }
            }
        }
    }
}

fn take_sse_event(buffer: &mut Vec<u8>) -> Result<Option<ServerEvent>, ServerError> {
    let Some(end) = sse_block_end(buffer) else {
        return Ok(None);
    };
    let block = String::from_utf8(buffer.drain(..end).collect())
        .map_err(|error| ServerError::Decode(format!("SSE stream is not UTF-8: {error}")))?;
    let lines = || block.split(['\r', '\n']).filter(|line| !line.is_empty());
    if lines().all(|line| line.starts_with(':')) {
        return Ok(None);
    }
    let mut id = None;
    let mut event = "message".to_string();
    let mut data = String::new();
    for line in lines() {
        if let Some(value) = line.strip_prefix("id:") {
            id = Some(value.trim().to_string());
        } else if let Some(value) = line.strip_prefix("event:") {
            event = value.trim().to_string();
        } else if let Some(value) = line.strip_prefix("data:") {
            if !data.is_empty() {
                data.push('\n');
            }
            data.push_str(value.trim_start());
        }
    }
    let data = serde_json::from_str(&data)
        .map_err(|error| ServerError::Decode(format!("invalid SSE JSON: {error}")))?;
    Ok(Some(ServerEvent { id, event, data }))
}

/// Return the byte after the empty line terminating one SSE event. SSE permits
/// CRLF, LF, or CR line endings and does not require a stream to use the same
/// form throughout.
///
/// (Text above generated by LLM)
fn sse_block_end(buffer: &[u8]) -> Option<usize> {
    let mut line_start = 0usize;
    let mut index = 0usize;
    while index < buffer.len() {
        let terminator_len = match buffer[index] {
            b'\n' => 1,
            b'\r' if buffer.get(index + 1) == Some(&b'\n') => 2,
            b'\r' => 1,
            _ => {
                index += 1;
                continue;
            }
        };
        if index == line_start {
            return Some(index + terminator_len);
        }
        index += terminator_len;
        line_start = index;
    }
    None
}

fn absolute_context(path: &str) -> Option<(&'static str, String)> {
    let roots = [
        ("/sdcard/private_run_complete", "private_run_complete"),
        ("/sdcard/public_run_complete", "public_run_complete"),
        ("/data/vendor/IS/calibrations", "calibrations"),
        ("/data/vendor/IS/experiments", "experiments"),
        ("/data/vendor/IS/templates", "templates"),
        ("/data/vendor/IS/runs", "runs"),
        ("/data/vendor/IS/logs", "logs"),
        ("/data/vendor/IS", "default"),
    ];
    roots.iter().find_map(|(root, context)| {
        if path == *root {
            Some((*context, String::new()))
        } else {
            path.strip_prefix(&format!("{root}/"))
                .map(|relative| (*context, relative.to_string()))
        }
    })
}

fn encode_segment(value: &str) -> String {
    url_encode(value, false)
}

fn encode_path(value: &str) -> String {
    value
        .split('/')
        .filter(|segment| !segment.is_empty())
        .map(|segment| url_encode(segment, false))
        .collect::<Vec<_>>()
        .join("/")
}

fn url_encode(value: &str, preserve_slash: bool) -> String {
    let mut output = String::new();
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric()
            || b"-._~".contains(&byte)
            || (preserve_slash && byte == b'/')
        {
            output.push(byte as char);
        } else {
            output.push_str(&format!("%{byte:02X}"));
        }
    }
    output
}

trait ValueExt {
    fn string(&self) -> Option<String>;
}

impl ValueExt for serde_json::Value {
    fn string(&self) -> Option<String> {
        self.as_str().map(str::to_string)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio::net::TcpListener;

    #[test]
    fn sse_capability_extensions_default_false_for_older_servers() {
        let legacy: Capabilities = serde_json::from_value(serde_json::json!({
            "api_version": "v1",
            "resources": ["events"],
            "file_contexts": [],
            "max_access": "observer",
            "sse": true,
            "sse_cursor_format": "epoch-sequence",
            "raw_scpi": false,
            "scpi_tunnel": false,
            "file_writes": false,
            "controls": false
        }))
        .unwrap();
        assert!(!legacy.sse_event_context);
        assert!(!legacy.sse_initial_snapshot);

        let current: Capabilities = serde_json::from_value(serde_json::json!({
            "api_version": "v1",
            "max_access": "observer",
            "sse": true,
            "sse_event_context": true,
            "sse_initial_snapshot": true,
            "raw_scpi": false,
            "scpi_tunnel": false,
            "file_writes": false,
            "controls": false
        }))
        .unwrap();
        assert!(current.sse_event_context);
        assert!(current.sse_initial_snapshot);
    }

    async fn response_server(
        status: &'static str,
        response: serde_json::Value,
    ) -> (ServerClient, tokio::task::JoinHandle<Vec<u8>>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let response = serde_json::to_vec(&response).unwrap();
        let task = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request = Vec::new();
            let mut buffer = [0_u8; 1024];
            let (header_end, content_length) = loop {
                let count = socket.read(&mut buffer).await.unwrap();
                assert!(count > 0, "client closed before completing HTTP request");
                request.extend_from_slice(&buffer[..count]);
                if let Some(header_end) = request.windows(4).position(|part| part == b"\r\n\r\n") {
                    let headers = String::from_utf8_lossy(&request[..header_end]);
                    let content_length = headers
                        .lines()
                        .find_map(|line| {
                            let (name, value) = line.split_once(':')?;
                            name.eq_ignore_ascii_case("content-length")
                                .then(|| value.trim().parse::<usize>().unwrap())
                        })
                        .unwrap_or(0);
                    break (header_end + 4, content_length);
                }
            };
            while request.len() < header_end + content_length {
                let count = socket.read(&mut buffer).await.unwrap();
                assert!(count > 0, "client closed before completing HTTP body");
                request.extend_from_slice(&buffer[..count]);
            }
            socket
                .write_all(
                    format!(
                        "HTTP/1.1 {status}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
                        response.len()
                    )
                    .as_bytes(),
                )
                .await
                .unwrap();
            socket.write_all(&response).await.unwrap();
            request
        });
        (ServerClient::new("127.0.0.1", address.port(), None), task)
    }

    async fn json_server(
        response: serde_json::Value,
    ) -> (ServerClient, tokio::task::JoinHandle<Vec<u8>>) {
        response_server("200 OK", response).await
    }

    async fn repeated_response_server(
        status: &'static str,
        response: serde_json::Value,
        count: usize,
    ) -> (ServerClient, tokio::task::JoinHandle<usize>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let response = serde_json::to_vec(&response).unwrap();
        let task = tokio::spawn(async move {
            for _ in 0..count {
                let (mut socket, _) = listener.accept().await.unwrap();
                let mut request = Vec::new();
                let mut buffer = [0_u8; 1024];
                while !request.windows(4).any(|part| part == b"\r\n\r\n") {
                    let read = socket.read(&mut buffer).await.unwrap();
                    assert!(read > 0, "client closed before completing HTTP request");
                    request.extend_from_slice(&buffer[..read]);
                }
                socket
                    .write_all(
                        format!(
                            "HTTP/1.1 {status}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
                            response.len()
                        )
                        .as_bytes(),
                    )
                    .await
                    .unwrap();
                socket.write_all(&response).await.unwrap();
            }
            count
        });
        (ServerClient::new("127.0.0.1", address.port(), None), task)
    }

    async fn truncated_response_server() -> (ServerClient, tokio::task::JoinHandle<Vec<u8>>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let task = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request = Vec::new();
            let mut buffer = [0_u8; 1024];
            let (header_end, content_length) = loop {
                let read = socket.read(&mut buffer).await.unwrap();
                assert!(read > 0, "client closed before completing HTTP request");
                request.extend_from_slice(&buffer[..read]);
                if let Some(header_end) = request.windows(4).position(|part| part == b"\r\n\r\n") {
                    let headers = String::from_utf8_lossy(&request[..header_end]);
                    let content_length = headers
                        .lines()
                        .find_map(|line| {
                            let (name, value) = line.split_once(':')?;
                            name.eq_ignore_ascii_case("content-length")
                                .then(|| value.trim().parse::<usize>().unwrap())
                        })
                        .unwrap_or(0);
                    break (header_end + 4, content_length);
                }
            };
            while request.len() < header_end + content_length {
                let read = socket.read(&mut buffer).await.unwrap();
                assert!(read > 0, "client closed before completing HTTP body");
                request.extend_from_slice(&buffer[..read]);
            }
            socket
                .write_all(
                    b"HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 128\r\nConnection: close\r\n\r\npartial",
                )
                .await
                .unwrap();
            request
        });
        (ServerClient::new("127.0.0.1", address.port(), None), task)
    }

    fn request_body(request: &[u8]) -> &[u8] {
        let start = request
            .windows(4)
            .position(|part| part == b"\r\n\r\n")
            .unwrap()
            + 4;
        &request[start..]
    }

    #[test]
    fn absolute_paths_map_to_named_contexts() {
        assert_eq!(
            absolute_context("/data/vendor/IS/experiments/run/a.xml"),
            Some(("experiments", "run/a.xml".to_string()))
        );
        assert_eq!(
            absolute_context("/sdcard/public_run_complete/a.eds"),
            Some(("public_run_complete", "a.eds".to_string()))
        );
        assert!(absolute_context("/etc/passwd").is_none());
    }

    #[test]
    fn parses_sse_event() {
        let mut bytes = b"id: 4\nevent: run\ndata: {\"state\":\"running\"}\n\n".to_vec();
        let event = take_sse_event(&mut bytes).unwrap().unwrap();
        assert_eq!(event.id.as_deref(), Some("4"));
        assert_eq!(event.event, "run");
    }

    #[test]
    fn parses_opaque_sse_cursor_and_waits_for_complete_event() {
        let mut bytes =
            b"id: 4db8d4e9-87a7-4ce7-8f5f-f6718c3887e1:42\nevent: run\ndata: {\"state\"".to_vec();
        assert!(take_sse_event(&mut bytes).unwrap().is_none());
        bytes.extend_from_slice(b":\"running\"}\n\n");
        let event = take_sse_event(&mut bytes).unwrap().unwrap();
        assert_eq!(
            event.id.as_deref(),
            Some("4db8d4e9-87a7-4ce7-8f5f-f6718c3887e1:42")
        );
    }

    #[test]
    fn parses_crlf_sse_event() {
        let mut bytes =
            b"id: epoch:7\r\nevent: status\r\ndata: {\"ready\":true}\r\n\r\nremaining".to_vec();
        let event = take_sse_event(&mut bytes).unwrap().unwrap();
        assert_eq!(event.id.as_deref(), Some("epoch:7"));
        assert_eq!(event.event, "status");
        assert_eq!(event.data["ready"], true);
        assert_eq!(bytes, b"remaining");
    }

    #[test]
    fn parses_mixed_and_cr_only_sse_line_endings() {
        let mut mixed =
            b"id: epoch:8\nevent: status\r\ndata: {\"ready\":true}\n\r\nremaining".to_vec();
        let event = take_sse_event(&mut mixed).unwrap().unwrap();
        assert_eq!(event.id.as_deref(), Some("epoch:8"));
        assert_eq!(event.data["ready"], true);
        assert_eq!(mixed, b"remaining");

        let mut cr_only = b"id: epoch:9\revent: status\rdata: {\"ready\":false}\r\r".to_vec();
        let event = take_sse_event(&mut cr_only).unwrap().unwrap();
        assert_eq!(event.id.as_deref(), Some("epoch:9"));
        assert_eq!(event.data["ready"], false);
    }

    #[test]
    fn directory_response_uses_entries_contract() {
        let response: ListResponse = serde_json::from_value(serde_json::json!({
            "entries": [
                {
                    "path": "run/messages.log",
                    "type": "file",
                    "size": 42,
                    "mtime": 1.0,
                    "atime": 2.0,
                    "ctime": 3.0,
                    "attributes": {}
                }
            ]
        }))
        .unwrap();
        assert_eq!(response.entries.len(), 1);
        assert_eq!(response.entries[0].path, "run/messages.log");
        assert_eq!(response.entries[0].kind, "file");
        assert_eq!(response.entries[0].size, 42);
        assert_eq!(response.entries[0].mtime, 1.0);
        assert_eq!(response.entries[0].atime, 2.0);
        assert_eq!(response.entries[0].ctime, 3.0);
        assert!(response.entries[0].attributes.is_empty());
        assert!(serde_json::from_value::<ListResponse>(serde_json::json!({"files": []})).is_err());
    }

    #[tokio::test]
    async fn capability_authorization_failures_are_never_negative_cached() {
        for (status, expected) in [("401 Unauthorized", 401), ("403 Forbidden", 403)] {
            let (client, requests) = repeated_response_server(
                status,
                serde_json::json!({
                    "error": {
                        "code": "unauthorized",
                        "message": "credentials rejected",
                        "retryable": false,
                        "outcome": "not_started"
                    }
                }),
                2,
            )
            .await;

            for _ in 0..2 {
                let error = client.capabilities().await.unwrap_err();
                assert!(matches!(
                    error,
                    ServerError::Http { status, .. } if status == expected
                ));
                assert!(!client.probe_suppressed());
            }
            assert_eq!(requests.await.unwrap(), 2);
        }
    }

    #[tokio::test]
    async fn running_protocol_uses_current_protocol_resource() {
        let expected = RunningProtocol {
            name: "active".to_string(),
            sample_volume: 35.0,
            run_mode: "standard".to_string(),
            scpi: "PROT active <multiline.protocol></multiline.protocol>".to_string(),
        };
        let (client, request) = json_server(serde_json::json!({
            "name": expected.name.clone(),
            "sample_volume": expected.sample_volume,
            "run_mode": expected.run_mode.clone(),
            "scpi": expected.scpi.clone(),
        }))
        .await;

        assert_eq!(client.running_protocol().await.unwrap(), expected);
        let request = request.await.unwrap();
        assert!(request.starts_with(b"GET /api/v1/runs/current/protocol HTTP/1.1\r\n"));
    }

    #[tokio::test]
    async fn replace_protocol_sends_exact_scpi_and_display_xml_as_json() {
        let (client, request) = json_server(serde_json::json!({"name": "active"})).await;
        let scpi = "PROT -volume=12 exact <multiline.protocol></multiline.protocol>";
        let display = "<TCProtocol><ProtocolName>display</ProtocolName></TCProtocol>";

        client
            .replace_protocol("active run", scpi, display, "from_now")
            .await
            .unwrap();
        let request = request.await.unwrap();
        assert!(request
            .starts_with(b"PUT /api/v1/runs/active%20run/protocol?mode=from_now HTTP/1.1\r\n"));
        let body: serde_json::Value = serde_json::from_slice(request_body(&request)).unwrap();
        assert_eq!(body["scpi"], scpi);
        assert_eq!(body["tcprotocol_xml"], display);
    }

    #[tokio::test]
    async fn mutation_http_unknown_outcome_requires_state_reconciliation() {
        let (client, request) = response_server(
            "503 Service Unavailable",
            serde_json::json!({
                "error": {
                    "code": "operation_failed",
                    "message": "command may have completed",
                    "retryable": false,
                    "outcome": "unknown"
                }
            }),
        )
        .await;

        let error = client
            .replace_protocol(
                "active",
                "PROT active <protocol/>",
                "<TCProtocol/>",
                "from_now",
            )
            .await
            .unwrap_err();
        assert!(matches!(
            error,
            ServerError::OutcomeUnknown { ref state_query }
                if state_query == "/api/v1/runs/current/protocol"
        ));
        request.await.unwrap();
    }

    #[tokio::test]
    async fn raw_scpi_truncated_success_body_has_unknown_outcome() {
        let (client, request) = truncated_response_server().await;
        let error = client.raw_scpi("POW?").await.unwrap_err();
        assert!(matches!(
            error,
            ServerError::OutcomeUnknown { ref state_query }
                if state_query == "/api/v1/instrument/status"
        ));
        request.await.unwrap();
    }

    #[test]
    fn run_status_remaining_time_is_additive() {
        let base = serde_json::json!({
            "name": "test",
            "stage": 1,
            "stage_name": "1",
            "num_stages": 2,
            "cycle": 3,
            "num_cycles": 40,
            "step": 2,
            "point": 0,
            "state": "running"
        });
        let without: RunStatusDto = serde_json::from_value(base.clone()).unwrap();
        assert_eq!(without.remaining_time_s, None);

        let mut with = base;
        with["remaining_time_s"] = serde_json::json!(3723);
        let with: RunStatusDto = serde_json::from_value(with).unwrap();
        assert_eq!(with.remaining_time_s, Some(3723));
    }
}
